[package]
name = "zerodds-xmlc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "ZeroDDS DDS-XML CLI — Validator, Schema-Checker, Deployment-Renderer."
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-xmlc"
readme = "README.md"
keywords = ["dds", "xml", "validator", "deployment", "cli"]
categories = ["command-line-utilities", "development-tools"]
publish = true

[lints]
workspace = true

[[bin]]
name = "zerodds-xmlc"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
