[package]
name = "zerodds-xmlc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "DDS-XML validator, schema checker, deployment renderer"
publish = true

[lints]
workspace = true

[[bin]]
name = "zerodds-xmlc"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
