[package]
name = "zerodds-idl-ts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository = "https://github.com/zero-objects/zero-dds"
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-idl-ts"
readme = "README.md"
keywords = ["dds", "idl", "codegen", "typescript"]
categories = ["development-tools"]
authors.workspace = true
description = "OMG IDL4 → TypeScript Code-Generator (Browser + Node.js Targets) für ZeroDDS."
publish = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
zerodds-idl = { version = "1.0.0-rc.1", path = "../idl" }

[dev-dependencies]
insta = { workspace = true }
tempfile = "3"

