// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors

//! Ada endpoint ping-pong: the generated `idlc` codec (`Pp_Gen.Marshal` /
//! `Pp_Gen.Unmarshal`) plus the native Ada endpoint SDK (`Deep_Reading` XRCE
//! framing + protected-`Mailbox` transport over the C89 wire-core via `Zdw`),
//! driven over a real `GNAT.Sockets` UDP datagram — sync (own the run-loop) and
//! async (a reader task feeds a protected `Mailbox`, main blocks on a timed
//! entry call). Gated on `gprbuild`.
//!
//! The Ada core is the endpoint substrate on the defense-legacy topology: a
//! minimal, composable endpoint (typed codec + framing + datagram), not a full
//! DDS stack — RTPS/discovery/QoS are the Rust peer's job here.

#![allow(clippy::expect_used, clippy::panic, clippy::print_stderr)]

use std::process::{Child, Command, Stdio};

use zerodds_endpoint_e2e::{IDL, Peer, bind_peer, ping_pong};
use zerodds_idl::config::ParserConfig;
use zerodds_idl_ada::{AdaGenOptions, generate_ada_module};

fn gprbuild_available() -> bool {
    Command::new("gprbuild").arg("--version").output().is_ok()
}

/// The app: generated `Pp_Gen` codec + `Deep_Reading` SDK framing/transport over
/// a real UDP socket. `argv[1]` = mode (`sync`|`async`), `argv[2]` = peer port.
const MAIN_ADB: &str = r#"-- SPDX-License-Identifier: Apache-2.0
with Ada.Command_Line;      use Ada.Command_Line;
with Ada.Text_IO;           use Ada.Text_IO;
with Ada.Strings;           use Ada.Strings;
with Ada.Strings.Fixed;     use Ada.Strings.Fixed;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Ada.Streams;           use Ada.Streams;
with Interfaces;            use Interfaces;
with GNAT.Sockets;          use GNAT.Sockets;
with Pp_Gen;
with Deep_Reading;

procedure Main is

   --  Integer_32 image without Ada's leading blank ("1", not " 1").
   function Img (V : Interfaces.Integer_32) return String is
   begin
      return Trim (Interfaces.Integer_32'Image (V), Left);
   end Img;

   --  Generated Byte_Array (typed body) -> SDK Frame_Store.
   function To_FS (B : Pp_Gen.Byte_Array) return Deep_Reading.Frame_Store is
      FS : Deep_Reading.Frame_Store;
   begin
      for I in B'Range loop
         FS.Data (I) := Interfaces.Unsigned_8 (B (I));
      end loop;
      FS.Len := B'Length;
      return FS;
   end To_FS;

   --  SDK Frame_Store body -> generated Byte_Array for Unmarshal.
   function To_BA (FS : Deep_Reading.Frame_Store) return Pp_Gen.Byte_Array is
      B : Pp_Gen.Byte_Array (0 .. FS.Len - 1);
   begin
      for I in 0 .. FS.Len - 1 loop
         B (I) := Pp_Gen.Byte (FS.Data (I));
      end loop;
      return B;
   end To_BA;

   procedure Send_Frame (Sock : Socket_Type; To : Sock_Addr_Type;
                         FS : Deep_Reading.Frame_Store) is
      SEA  : Stream_Element_Array (0 .. Stream_Element_Offset (FS.Len) - 1);
      Last : Stream_Element_Offset;
   begin
      for I in 0 .. FS.Len - 1 loop
         SEA (Stream_Element_Offset (I)) := Stream_Element (FS.Data (I));
      end loop;
      Send_Socket (Sock, SEA, Last, To);
   end Send_Frame;

   --  Receive one datagram into a Frame_Store; Len=0 on timeout / empty.
   function Recv_Frame (Sock : Socket_Type) return Deep_Reading.Frame_Store is
      Recv : Stream_Element_Array (0 .. 511);
      Last : Stream_Element_Offset;
      From : Sock_Addr_Type;
      FS   : Deep_Reading.Frame_Store;
   begin
      Receive_Socket (Sock, Recv, Last, From);
      if Last < Recv'First then
         return FS;
      end if;
      for I in 0 .. Natural (Last) loop
         FS.Data (I) := Interfaces.Unsigned_8 (Recv (Stream_Element_Offset (I)));
      end loop;
      FS.Len := Natural (Last) + 1;
      return FS;
   exception
      when Socket_Error =>
         return FS;
   end Recv_Frame;

   procedure Print_Pong (Body_FS : Deep_Reading.Frame_Store) is
      P : constant Pp_Gen.Pong :=
        Pp_Gen.Unmarshal (To_BA (Body_FS), Pp_Gen.Little);
   begin
      Put_Line ("PONG seq=" & Img (P.seq)
                & " reply=" & To_String (P.reply));
   end Print_Pong;

   --  Sync: own the run-loop -- send, then block on the socket (poll idiom).
   procedure Run_Sync (Sock : Socket_Type; Peer : Sock_Addr_Type;
                       Framed : Deep_Reading.Frame_Store) is
      In_FS   : Deep_Reading.Frame_Store;
      Body_FS : Deep_Reading.Frame_Store;
   begin
      Send_Frame (Sock, Peer, Framed);
      In_FS := Recv_Frame (Sock);
      if In_FS.Len = 0 then
         Put_Line ("sync: no pong");
         Set_Exit_Status (1);
         return;
      end if;
      Body_FS := Deep_Reading.Deframe (In_FS);
      Print_Pong (Body_FS);
   end Run_Sync;

   --  Async: a reader task pulls the datagram and forwards the deframed body
   --  into a protected Mailbox; main blocks on a timed entry call. The
   --  idiomatic Ada task + protected-object concurrency model.
   procedure Run_Async (Sock : Socket_Type; Peer : Sock_Addr_Type;
                        Framed : Deep_Reading.Frame_Store) is
      Inbox : Deep_Reading.Mailbox;

      task Reader;
      task body Reader is
         In_FS   : Deep_Reading.Frame_Store;
         Body_FS : Deep_Reading.Frame_Store;
      begin
         In_FS := Recv_Frame (Sock);
         if In_FS.Len > 0 then
            Body_FS := Deep_Reading.Deframe (In_FS);
            if Body_FS.Len > 0 then
               Inbox.Deliver (Body_FS);
            end if;
         end if;
      end Reader;

      Body_FS : Deep_Reading.Frame_Store;
   begin
      Send_Frame (Sock, Peer, Framed);
      select
         Inbox.Receive (Body_FS);
         Print_Pong (Body_FS);
      or
         delay 12.0;
         Put_Line ("async: no pong");
         Set_Exit_Status (1);
      end select;
   end Run_Async;

   Mode      : constant String    := Argument (1);
   Peer_Port : constant Port_Type := Port_Type'Value (Argument (2));
   Peer      : constant Sock_Addr_Type :=
     (Family_Inet, Loopback_Inet_Addr, Peer_Port);

   Ping_Val : constant Pp_Gen.Ping :=
     (seq => 1, msg => To_Unbounded_String ("hello from app"));
   Framed   : constant Deep_Reading.Frame_Store :=
     Deep_Reading.Frame (1, To_FS (Pp_Gen.Marshal (Ping_Val, Pp_Gen.Little)));

   Sock : Socket_Type;
begin
   Create_Socket (Sock, Family_Inet, Socket_Datagram);
   Set_Socket_Option (Sock, Socket_Level, (Reuse_Address, True));
   Bind_Socket (Sock, (Family_Inet, Loopback_Inet_Addr, Any_Port));
   Set_Socket_Option (Sock, Socket_Level, (Receive_Timeout, 10.0));

   if Mode = "async" then
      Run_Async (Sock, Peer, Framed);
   else
      Run_Sync (Sock, Peer, Framed);
   end if;

   Close_Socket (Sock);
end Main;
"#;

/// GNAT project: the app (`.`) + the Ada SDK (`endpoints/ada/src`) + the C89
/// wire-core (`endpoints/c`). Only `zerodds_wire.c` is needed (defines the
/// `zdw_*` primitives `Zdw` imports); the endpoint/reflect/async C units are
/// excluded. `-gnat2022` for the SDK's square-bracket aggregates.
fn gpr(ada_src: &str, c_src: &str, c_inc: &str) -> String {
    format!(
        "project Pp is\n\
         \x20  for Languages use (\"Ada\", \"C\");\n\
         \x20  for Source_Dirs use (\".\", \"{ada_src}\", \"{c_src}\", \"{c_inc}\");\n\
         \x20  for Object_Dir use \"obj\";\n\
         \x20  for Exec_Dir use \".\";\n\
         \x20  for Main use (\"main.adb\");\n\
         \x20  for Excluded_Source_Files use\n\
         \x20    (\"zerodds_endpoint.c\", \"zerodds_reflect.c\", \"zerodds_async.c\");\n\
         \x20  package Compiler is\n\
         \x20     for Default_Switches (\"Ada\") use (\"-g\", \"-gnat2022\");\n\
         \x20     for Default_Switches (\"C\") use (\"-std=c89\", \"-O2\");\n\
         \x20  end Compiler;\n\
         \x20  package Binder is\n\
         \x20     for Default_Switches (\"Ada\") use (\"-Es\");\n\
         \x20  end Binder;\n\
         end Pp;\n"
    )
}

/// Generate the app, compile it once with gprbuild, return the exe path.
fn build_app(dir: &std::path::Path) -> std::path::PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    let canon = |rel: &str| {
        std::path::Path::new(&format!("{manifest}/{rel}"))
            .canonicalize()
            .expect("endpoints path")
            .display()
            .to_string()
    };
    let ada_src = canon("../../endpoints/ada/src");
    let c_src = canon("../../endpoints/c/src");
    let c_inc = canon("../../endpoints/c/include");

    let ast = zerodds_idl::parse(IDL, &ParserConfig::default()).expect("parse");
    let m = generate_ada_module(
        &ast,
        &AdaGenOptions {
            package_name: "Pp_Gen".to_string(),
            ..Default::default()
        },
    )
    .expect("gen ada");

    std::fs::write(dir.join("pp_gen.ads"), &m.spec).expect("write ads");
    std::fs::write(dir.join("pp_gen.adb"), &m.body).expect("write adb");
    std::fs::write(dir.join("main.adb"), MAIN_ADB).expect("write main");
    std::fs::write(dir.join("pp.gpr"), gpr(&ada_src, &c_src, &c_inc)).expect("write gpr");

    let out = Command::new("gprbuild")
        .arg("-p")
        .arg("-P")
        .arg("pp.gpr")
        .current_dir(dir)
        .output()
        .expect("run gprbuild");
    assert!(
        out.status.success(),
        "gprbuild failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    dir.join("main")
}

fn spawn(exe: &std::path::Path, mode: &str, port: u16) -> Child {
    Command::new(exe)
        .arg(mode)
        .arg(port.to_string())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn ada app")
}

fn endpoint_case(mode: &str) {
    if !gprbuild_available() {
        eprintln!("SKIP ada endpoint {mode}: `gprbuild` not on PATH");
        return;
    }
    let dir = std::env::temp_dir().join(format!("pp_ada_{mode}_{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("mkdir");
    let exe = build_app(&dir);
    let peer: Peer = bind_peer().expect("bind peer");
    let child = spawn(&exe, mode, peer.port);
    ping_pong(&peer, child, &format!("ada/{mode}"));
}

#[test]
fn ada_endpoint_sync() {
    endpoint_case("sync");
}

#[test]
fn ada_endpoint_async() {
    endpoint_case("async");
}
