[package]
name = "zerodds-corba-ccm-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "CCM components library for zerodds-corba-ccm: DDS bridge, persistence storage, telemetry components."
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-corba-ccm-lib"
readme = "README.md"
keywords = ["dds", "corba", "ccm", "components", "omg"]
categories = ["network-programming", "api-bindings"]
publish = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
zerodds-corba-ccm = { version = "1.0.0-rc.3.1", path = "../corba-ccm" }
