[package]
name = "zerodds-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Conformance-Test-Vector-Runner: Autobahn/OASIS/h2spec/CoAP-Plugtest/DDS-XML"
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-conformance"
readme = "README.md"
keywords = ["dds", "conformance", "test", "interop"]
categories = ["development-tools::testing"]
publish = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
zerodds-websocket-bridge = { version = "1.0.0-rc.7", path = "../websocket-bridge" }
zerodds-mqtt-bridge = { version = "1.0.0-rc.7", path = "../mqtt-bridge" }
zerodds-http2 = { version = "1.0.0-rc.7", path = "../http2" }
zerodds-hpack = { version = "1.0.0-rc.7", path = "../hpack" }
zerodds-grpc-bridge = { version = "1.0.0-rc.7", path = "../grpc-bridge" }
zerodds-coap-bridge = { version = "1.0.0-rc.7", path = "../coap-bridge" }
zerodds-xml-wire = { version = "1.0.0-rc.7", path = "../zerodds-xml-wire" }

[dev-dependencies]
zerodds-dotnet-build-lock = { path = "../dotnet-build-lock" }
