[package]
name = "zerodds-monitor-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "ZeroDDS Monitoring-CLI — Live-Snapshot oder Prometheus-/metrics-Server für ZeroDDS-Runtime."
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-monitor"
readme = "README.md"
keywords = ["dds", "monitor", "prometheus", "metrics", "cli"]
categories = ["command-line-utilities", "development-tools::profiling"]
publish = true

[lints]
workspace = true

[[bin]]
name = "zerodds-monitor"
path = "src/main.rs"

[lib]
name = "zerodds_monitor_cli"
path = "src/lib.rs"

[dependencies]
zerodds-cli-common  = { version = "1.0.0-rc.5", path = "../cli-common" }
zerodds-monitor-lib = { version = "1.0.0-rc.5", path = "../../crates/monitor", package = "zerodds-monitor" }
zerodds-dcps        = { version = "1.0.0-rc.5", path = "../../crates/dcps" }
