// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Top-level emitter: AST → Rust string.

use zerodds_idl::ast::Annotation;
use zerodds_idl::ast::types::{
    ConstDecl, ConstExpr, ConstType, ConstrTypeDecl, Declarator, Definition, ExceptDecl, Export,
    FloatingType, InterfaceDcl, Literal, LiteralKind, ModuleDef, Specification, StructDcl,
    TypeDecl, UnionDcl,
};
use zerodds_idl::semantics::annotations::PlacementKind;

use crate::error::Result;
use crate::type_map::{escape_keyword, rust_integer_type, rust_type_for};
use crate::verbatim::emit_verbatim_at;

/// Outer `#[allow(...)]` for a type declaration whose members may carry
/// non-`snake_case` IDL identifiers (struct/exception/bitset fields).
///
/// Emitted as an OUTER attribute on the item, never as a file-level inner
/// attribute (`#![...]`) — inner attributes are rejected when the generated
/// file is pulled into a parent module via `include!` (issue #26). Placing
/// the allow on the item keeps every generated file `include!`-composable.
pub(crate) const TYPE_LINT_ALLOW: &str = "#[allow(non_snake_case)]\n";

/// Outer `#[allow(...)]` for a generated `impl` block: its methods can be
/// long (`clippy::too_many_lines`) and their locals mirror IDL field names
/// (`non_snake_case`). Outer, per-impl — same `include!` rationale as
/// [`TYPE_LINT_ALLOW`].
pub(crate) const IMPL_LINT_ALLOW: &str = "#[allow(clippy::too_many_lines, non_snake_case)]\n";

/// Returns the annotation list of a top-level `Definition`, if the variant
/// carries one. Used for file-level `@verbatim` emission (BEGIN_FILE/END_FILE).
fn top_level_annotations(d: &Definition) -> Option<&[Annotation]> {
    match d {
        Definition::Module(m) => Some(&m.annotations),
        Definition::Type(TypeDecl::Constr(c)) => match c {
            ConstrTypeDecl::Struct(StructDcl::Def(s)) => Some(&s.annotations),
            ConstrTypeDecl::Union(UnionDcl::Def(u)) => Some(&u.annotations),
            ConstrTypeDecl::Enum(e) => Some(&e.annotations),
            _ => None,
        },
        Definition::Type(TypeDecl::Typedef(t)) => Some(&t.annotations),
        Definition::Const(c) => Some(&c.annotations),
        Definition::Except(e) => Some(&e.annotations),
        _ => None,
    }
}

/// Options for the code generator.
#[derive(Debug, Clone, Default)]
pub struct RustGenOptions {
    /// Header comment placed at the top of the generated file. Included verbatim.
    pub header_comment: Option<String>,
    /// CDR-only mode for the CORBA/GIOP path: omits the `DdsType` impl
    /// (XCDR2 + `field_value`) that pulls in `zerodds_dcps`/`zerodds_types`.
    /// Only type declarations and classic `CdrEncode`/`CdrDecode` remain —
    /// the sole wire representation for CORBA requests/replies (CDR §15.3).
    pub cdr_only: bool,
}

/// Generates a single Rust module file from a parsed IDL spec.
///
/// # Errors
/// `Unsupported` for IDL constructs outside the DDS DataType scope.
pub fn generate_rust_module(spec: &Specification, opts: &RustGenOptions) -> Result<String> {
    // `any` target: cdr_only (CORBA path) → CorbaAny, otherwise DDS → DdsAny.
    crate::type_map::set_any_target_corba(opts.cdr_only);
    // This pass emits only data types, no interface references — clear the
    // interface-ref set (no stale state from a previous corba-rust run in
    // the same process, e.g. a two-pass build.rs).
    crate::type_map::set_interface_refs(core::iter::empty());
    // Record struct/enum/typedef names so `field_value` resolves scoped fields
    // (struct → forward, enum → int, typedef-to-primitive → leaf).
    crate::type_map::register_types_for_field_value(spec);
    // A29: reset the emit-scope stack so `rust_scoped`'s `super::` depth starts
    // from the crate/include root (no stale depth from a prior run).
    crate::type_map::scope_reset();
    // #24: build the full-spec named-type index ("Path A",
    // `zerodds_idl::semantics::build_type_registry`) once, so
    // `TYPE_IDENTIFIER` codegen ("Path B", `type_identifier.rs`) can
    // resolve typedef/enum/sequence/map/nested-struct member types
    // instead of nulling the whole struct's identity on the first
    // non-primitive/non-string member.
    crate::type_identifier::register_spec(spec);
    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: Apache-2.0\n");
    if let Some(c) = &opts.header_comment {
        for line in c.lines() {
            out.push_str("// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("// Auto-generated by `zerodds-idl-rust`. Do not edit by hand.\n");
    out.push('\n');
    // No file-level inner attributes (`#![...]`) and no top-level `use`: both
    // break `include!` composition. Inner attributes are rejected inside a
    // parent module (issue #26), and a top-level `use` collides (E0252) when
    // two generated files are `include!`d into the same module (issue #25).
    // Lint allows live on the individual items (see `TYPE_LINT_ALLOW`/
    // `IMPL_LINT_ALLOW`); every reference to `zerodds_cdr`/`zerodds_dcps`/
    // `zerodds_types` is fully qualified, so no `use` is needed. IDL
    // identifiers may be camelCase (e.g. NGVA headlessCamelCase per AEP-4754
    // Vol V §8.1.3); generated structs keep the IDL field spelling, hence the
    // per-item `non_snake_case` allow.

    // §7.2.2.4.8 — `@verbatim(placement=BEGIN_FILE)` from all top-level defs
    // (source order). Emitted after the crate preamble, before any type.
    for def in &spec.definitions {
        if let Some(anns) = top_level_annotations(def) {
            emit_verbatim_at(&mut out, "", anns, PlacementKind::BeginFile);
        }
    }

    // IDL modules may be REOPENED (`module A { … }; module A { … };`,
    // §7.4.2). Rust rejects two `pub mod A` at the same scope (E0428), so merge
    // same-named modules (recursively) into one before emitting.
    let merged = merge_modules_deep(&spec.definitions);
    let mut path: Vec<String> = Vec::new();
    for def in &merged {
        emit_definition(&mut out, def, &mut path, opts.cdr_only)?;
    }

    // §7.2.2.4.8 — `@verbatim(placement=END_FILE)` from all top-level defs.
    for def in &spec.definitions {
        if let Some(anns) = top_level_annotations(def) {
            emit_verbatim_at(&mut out, "", anns, PlacementKind::EndFile);
        }
    }

    Ok(out)
}

/// Appends only the data-type definitions (struct/enum/union/exception/typedef/
/// bitset) from a spec to `out` — without a file header, `use` line, or
/// module wrapper. Used by the CORBA code generator (`zerodds-corba-rust`),
/// which emits types and interfaces into a shared module.
///
/// # Errors
/// `Unsupported` for IDL constructs outside the DataType scope.
pub fn append_data_types(out: &mut String, spec: &Specification, cdr_only: bool) -> Result<()> {
    crate::type_map::register_types_for_field_value(spec);
    crate::type_map::scope_reset();
    // #24: see `generate_rust_module` — same full-spec registry build,
    // needed here too since this entry point (used by `zerodds-corba-rust`)
    // also reaches `struct_emit`'s TYPE_IDENTIFIER codegen.
    crate::type_identifier::register_spec(spec);
    let merged = merge_modules_deep(&spec.definitions);
    let mut path: Vec<String> = Vec::new();
    for def in &merged {
        emit_definition(out, def, &mut path, cdr_only)?;
    }
    Ok(())
}

/// Coalesces reopened IDL modules (§7.4.2): same-named modules at one scope are
/// merged into the first occurrence (its inner definitions concatenated in
/// source order), recursively. Rust has no module reopening, so without this a
/// reopened `module A` would emit two `pub mod A` and fail to compile (E0428).
/// Non-module definitions pass through unchanged, in order.
/// zerodds-lint: recursion-depth 16
fn merge_modules_deep(defs: &[Definition]) -> Vec<Definition> {
    let mut result: Vec<Definition> = Vec::new();
    let mut index: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for def in defs {
        match def {
            Definition::Module(m) => {
                if let Some(&i) = index.get(&m.name.text) {
                    if let Definition::Module(existing) = &mut result[i] {
                        existing.definitions.extend(m.definitions.iter().cloned());
                    }
                } else {
                    index.insert(m.name.text.clone(), result.len());
                    result.push(Definition::Module(m.clone()));
                }
            }
            other => result.push(other.clone()),
        }
    }
    for def in &mut result {
        if let Definition::Module(m) = def {
            m.definitions = merge_modules_deep(&m.definitions);
        }
    }
    result
}

/// zerodds-lint: recursion-depth 16
/// IDL module nesting — 16 levels are sufficient for all known OMG spec IDL files.
fn emit_definition(
    out: &mut String,
    def: &Definition,
    path: &mut Vec<String>,
    cdr_only: bool,
) -> Result<()> {
    match def {
        Definition::Module(m) => emit_module(out, m, path, cdr_only),
        Definition::Type(t) => emit_type_decl(out, t, path, cdr_only),
        Definition::Except(e) => {
            emit_exception(out, e)?;
            out.push('\n');
            Ok(())
        }
        // IDL `const` → a Rust `pub const` binding (finding A5). Previously
        // dropped silently (the catch-all `Ok(())`), so a named constant an
        // application referenced from generated IDL disappeared. Emitted for
        // the primitive/string const types; a `fixed`/scoped-typed const has
        // no direct Rust literal form and is skipped (unchanged output there).
        Definition::Const(c) => {
            emit_const(out, c);
            Ok(())
        }
        // Emit interface-nested exceptions as struct types — the CORBA
        // code generator (corba-rust) references them in the `{Iface}Error`
        // enum, and their RepositoryId carries the interface scope (e.g.
        // IDL:omg.org/CosNaming/NamingContext/NotFound:1.0). DDS IDL has no
        // interfaces, so this is a no-op in the DDS path.
        Definition::Interface(InterfaceDcl::Def(i)) => {
            // F.1 / A38: an interface body may declare nested types and
            // constants (IDL §7.4.3). They are part of the interface's public
            // surface and were previously discarded (only exceptions were
            // emitted). Emit them at the current scope — matching how the
            // interface-nested exceptions below are emitted flat — so a member
            // referencing `Iface::NestedType` resolves.
            for ex in &i.exports {
                match ex {
                    Export::Type(td) => emit_type_decl(out, td, path, cdr_only)?,
                    Export::Const(c) => emit_const(out, c),
                    _ => {}
                }
            }
            for ex in &i.exports {
                if let Export::Except(e) = ex {
                    emit_exception(out, e)?;
                    out.push('\n');
                }
            }
            // F.1 item 11: an interface with operations is an RPC/method
            // surface. In the DDS path (default mode) we emit real native Rust
            // DDS-RPC codegen — typed `<Service>Requester`/`<Service>Replier`
            // wrappers around the `zerodds_rpc` runtime (see [`crate::rpc`]).
            // In `cdr_only` mode (the CORBA/GIOP path) the DDS-RPC runtime
            // (`zerodds_dcps`/`zerodds_rpc`) is deliberately excluded, so we
            // leave a visible note instead; CORBA interface stubs come from
            // `zerodds-corba-rust`.
            let op_count = i
                .exports
                .iter()
                .filter(|e| matches!(e, Export::Op(_)))
                .count();
            if op_count > 0 {
                if cdr_only {
                    out.push_str(&format!(
                        "// zerodds-idl-rust: interface `{}` ({op_count} operation(s)) — CORBA \
                         path (cdr_only); DDS-RPC stubs are produced by `zerodds-corba-rust`, \
                         not emitted here.\n\n",
                        i.name.text
                    ));
                } else {
                    crate::rpc::emit_service_rpc(out, i, path)?;
                }
            }
            Ok(())
        }
        // Remaining CORBA/component declarations are not handled in the
        // Rust code generator (ZeroDDS Rust API is DDS-centric).
        _ => Ok(()),
    }
}

/// zerodds-lint: recursion-depth 16
fn emit_module(
    out: &mut String,
    m: &ModuleDef,
    path: &mut Vec<String>,
    cdr_only: bool,
) -> Result<()> {
    out.push_str("pub mod ");
    out.push_str(&escape_keyword(&m.name.text));
    out.push_str(" {\n");
    // No `use` here either: the module body fully qualifies every external
    // path, so an inner `use` would only be a dead (and, on `include!`,
    // colliding) import.
    // Push the raw IDL module name (not Rust-escaped) so TYPE_NAME
    // emits spec-conform `Module::Sub::Struct`. Conformance §3 / §5.
    path.push(m.name.text.clone());
    // Mirror the scope in type_map so `rust_scoped` computes the correct
    // `super::` depth for cross-module references (A29).
    crate::type_map::scope_push(&m.name.text);
    for inner in &m.definitions {
        let mut inner_out = String::new();
        emit_definition(&mut inner_out, inner, path, cdr_only)?;
        // Indent
        for line in inner_out.lines() {
            if line.is_empty() {
                out.push('\n');
            } else {
                out.push_str("    ");
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    crate::type_map::scope_pop();
    path.pop();
    out.push_str("}\n\n");
    Ok(())
}

/// Annotation list carried by a `TypeDecl`, for per-declaration `@verbatim`
/// (BEFORE_DECLARATION / AFTER_DECLARATION). `None` for forward decls (which
/// emit nothing) and `native`.
fn type_decl_annotations(td: &TypeDecl) -> Option<&[Annotation]> {
    match td {
        TypeDecl::Constr(ConstrTypeDecl::Struct(StructDcl::Def(s))) => Some(&s.annotations),
        TypeDecl::Constr(ConstrTypeDecl::Union(UnionDcl::Def(u))) => Some(&u.annotations),
        TypeDecl::Constr(ConstrTypeDecl::Enum(e)) => Some(&e.annotations),
        TypeDecl::Constr(ConstrTypeDecl::Bitset(b)) => Some(&b.annotations),
        TypeDecl::Constr(ConstrTypeDecl::Bitmask(m)) => Some(&m.annotations),
        TypeDecl::Typedef(t) => Some(&t.annotations),
        _ => None,
    }
}

fn emit_type_decl(out: &mut String, td: &TypeDecl, path: &[String], cdr_only: bool) -> Result<()> {
    // §7.2.2.4.8 — `@verbatim(placement=BEFORE_DECLARATION)` before the type.
    if let Some(anns) = type_decl_annotations(td) {
        emit_verbatim_at(out, "", anns, PlacementKind::BeforeDeclaration);
    }
    match td {
        TypeDecl::Constr(ConstrTypeDecl::Struct(struct_dcl)) => {
            // StructDcl is a wrapper around Def/Forward.
            use zerodds_idl::ast::types::StructDcl;
            match struct_dcl {
                StructDcl::Def(s) => {
                    // #24: the struct's module-path scope, for
                    // TYPE_IDENTIFIER member resolution (innermost-scope-
                    // first IDL name lookup) inside `struct_emit`'s call
                    // into `type_identifier::struct_type_identifier_expr`.
                    crate::type_identifier::set_current_scope(path);
                    crate::struct_emit::emit_struct_with_mode(out, s, path, cdr_only)?;
                    out.push('\n');
                }
                StructDcl::Forward(_) => {
                    // Forward declarations are not needed in Rust
                    // (order is handled via visibility/module).
                }
            }
        }
        TypeDecl::Constr(ConstrTypeDecl::Enum(e)) => {
            crate::enum_emit::emit_enum(out, e)?;
            out.push('\n');
        }
        TypeDecl::Constr(ConstrTypeDecl::Union(u)) => {
            use zerodds_idl::ast::types::UnionDcl;
            match u {
                UnionDcl::Def(def) => {
                    crate::union_emit::emit_union(out, def)?;
                    out.push('\n');
                }
                UnionDcl::Forward(_) => {}
            }
        }
        TypeDecl::Typedef(td) => {
            crate::typedef_emit::emit_typedef(out, td)?;
        }
        TypeDecl::Constr(ConstrTypeDecl::Bitset(b)) => {
            crate::bitset_emit::emit_bitset(out, b)?;
            out.push('\n');
        }
        TypeDecl::Constr(ConstrTypeDecl::Bitmask(m)) => {
            crate::bitset_emit::emit_bitmask(out, m)?;
            out.push('\n');
        }
        // `native X;` is an opaque, platform-specific type without a
        // DDS wire representation — not emitted in the DataType codegen
        // (analogous to `const`).
        TypeDecl::Native(_) => {}
    }
    // §7.2.2.4.8 — `@verbatim(placement=AFTER_DECLARATION)` after the type
    // (this is the spec default placement).
    if let Some(anns) = type_decl_annotations(td) {
        emit_verbatim_at(out, "", anns, PlacementKind::AfterDeclaration);
    }
    Ok(())
}

/// Emits an IDL `exception` definition as a Rust struct + classic
/// `CdrEncode`/`CdrDecode` impls. CORBA exceptions are struct-like data
/// containers; on the wire they are marshalled like a struct
/// (CDR §15.3 — members in declaration order), embedded in the
/// `UserException` reply body (§15.4.2, behind the repository ID). The
/// generated interface code (`zerodds-corba-rust`) references them as an
/// error variant; the marshalling uses these impls.
fn emit_exception(out: &mut String, e: &ExceptDecl) -> Result<()> {
    use crate::struct_emit::{
        declarator_ident, emit_member_decode_let_with_reader, emit_member_encode_with_writer,
    };

    out.push_str("/// Generated by `zerodds-idl-rust` from IDL exception (CORBA 3.3 §7.4.10).\n");
    out.push_str(TYPE_LINT_ALLOW);
    out.push_str("#[derive(Debug, Clone, PartialEq, Default)]\n");
    out.push_str("pub struct ");
    out.push_str(&escape_keyword(&e.name.text));
    out.push_str(" {\n");
    for member in &e.members {
        let rust_ty = rust_type_for(&member.type_spec)?;
        for declarator in &member.declarators {
            let raw = match declarator {
                Declarator::Simple(n) => &n.text,
                Declarator::Array(a) => &a.name.text,
            };
            let name = escape_keyword(raw);
            out.push_str(&format!("    pub {name}: {rust_ty},\n"));
        }
    }
    out.push_str("}\n");

    // CdrEncode — members sequential (classic CDR, no DHEADER).
    let name = escape_keyword(&e.name.text);
    out.push('\n');
    out.push_str(IMPL_LINT_ALLOW);
    out.push_str(&format!("impl zerodds_cdr::CdrEncode for {name} {{\n"));
    out.push_str(
        "    fn encode(&self, writer: &mut zerodds_cdr::BufferWriter) -> ::core::result::Result<(), zerodds_cdr::EncodeError> {\n",
    );
    for member in &e.members {
        emit_member_encode_with_writer(out, member, "        ", "writer")?;
    }
    out.push_str("        ::core::result::Result::Ok(())\n");
    out.push_str("    }\n}\n");

    // CdrDecode — symmetric.
    out.push('\n');
    out.push_str(IMPL_LINT_ALLOW);
    out.push_str(&format!("impl zerodds_cdr::CdrDecode for {name} {{\n"));
    out.push_str(
        "    fn decode(reader: &mut zerodds_cdr::BufferReader<'_>) -> ::core::result::Result<Self, zerodds_cdr::DecodeError> {\n",
    );
    for member in &e.members {
        emit_member_decode_let_with_reader(out, member, "        ", "reader")?;
    }
    out.push_str("        ::core::result::Result::Ok(Self {\n");
    for member in &e.members {
        for declarator in &member.declarators {
            let field = declarator_ident(declarator);
            out.push_str(&format!("            {field},\n"));
        }
    }
    out.push_str("        })\n");
    out.push_str("    }\n}\n");
    Ok(())
}

/// Emits an IDL `const` declaration as a Rust `pub const` binding (finding A5).
///
/// Renders the primitive / string const types with a value literal of the
/// matching Rust type. Const types without a direct Rust literal form
/// (`fixed`, or a scoped/enum-typed const) are skipped — emitting nothing keeps
/// the previous behavior for those, so no ill-formed binding is produced.
fn emit_const(out: &mut String, c: &ConstDecl) {
    let (Some(rust_ty), Some(value)) = (
        const_rust_type(&c.type_),
        render_const_value(&c.type_, &c.value),
    ) else {
        return;
    };
    out.push_str("/// Generated by `zerodds-idl-rust` from IDL const.\n");
    out.push_str(&format!(
        "pub const {}: {rust_ty} = {value};\n\n",
        escape_keyword(&c.name.text)
    ));
}

/// Rust type of an IDL `const` type, or `None` when the const has no direct
/// Rust literal representation (`fixed`, scoped/enum, `long double`).
fn const_rust_type(ct: &ConstType) -> Option<String> {
    Some(match ct {
        ConstType::Integer(i) => rust_integer_type(*i).to_string(),
        ConstType::Floating(FloatingType::Float) => "f32".to_string(),
        ConstType::Floating(FloatingType::Double) => "f64".to_string(),
        // `long double` has no stable Rust type (see `rust_type_for`); skip.
        ConstType::Floating(FloatingType::LongDouble) => return None,
        ConstType::Char | ConstType::Octet => "u8".to_string(),
        ConstType::WideChar => "u16".to_string(),
        ConstType::Boolean => "bool".to_string(),
        ConstType::String { .. } => "&str".to_string(),
        ConstType::Fixed | ConstType::Scoped(_) => return None,
    })
}

/// Renders the value expression of a `const` as a Rust literal of its type.
fn render_const_value(ct: &ConstType, expr: &ConstExpr) -> Option<String> {
    match ct {
        ConstType::Boolean => {
            crate::type_map::const_expr_as_i128(expr).map(|v| (v != 0).to_string())
        }
        ConstType::Integer(_) | ConstType::Octet | ConstType::Char | ConstType::WideChar => {
            crate::type_map::const_expr_as_i128(expr).map(|v| v.to_string())
        }
        ConstType::Floating(_) => render_const_float(expr),
        ConstType::String { .. } => render_const_string(expr),
        ConstType::Fixed | ConstType::Scoped(_) => None,
    }
}

/// Renders a floating const value as a Rust `f32`/`f64` literal. A bare integer
/// literal (`const double X = 5;`) is normalised to `5f64`-compatible `5.0`.
fn render_const_float(expr: &ConstExpr) -> Option<String> {
    if let ConstExpr::Literal(Literal { kind, raw, .. }) = expr {
        if matches!(kind, LiteralKind::Floating | LiteralKind::Integer) {
            let trimmed = raw.trim_end_matches(['f', 'F', 'd', 'D', 'l', 'L']);
            let parsed: f64 = trimmed.parse().ok()?;
            // `{:?}` yields a round-trippable, always-decimal-pointed rendering
            // (`5.0`, `3.14`, `inf`→rejected below), which is valid Rust.
            if !parsed.is_finite() {
                return None;
            }
            return Some(format!("{parsed:?}"));
        }
    }
    // Folded arithmetic / named const → integer value rendered as a float.
    crate::type_map::const_expr_as_i128(expr).map(|v| format!("{:?}", v as f64))
}

/// Renders a string const value as a Rust `&str` literal. The IDL raw carries
/// the surrounding quotes; a wide-string `L"…"` prefix is stripped.
fn render_const_string(expr: &ConstExpr) -> Option<String> {
    if let ConstExpr::Literal(Literal { kind, raw, .. }) = expr {
        if matches!(kind, LiteralKind::String | LiteralKind::WideString) {
            let s = raw.trim();
            let s = s.strip_prefix('L').unwrap_or(s);
            if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
                return Some(s.to_string());
            }
        }
    }
    None
}
