// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Top-level emitter: AST → Rust string.

use zerodds_idl::ast::types::{
    ConstrTypeDecl, Declarator, Definition, ExceptDecl, Export, InterfaceDcl, ModuleDef,
    Specification, TypeDecl,
};

use crate::error::Result;
use crate::type_map::{escape_keyword, rust_type_for};

/// Options for the code generator.
#[derive(Debug, Clone, Default)]
pub struct RustGenOptions {
    /// Header comment placed at the top of the generated file. Included verbatim.
    pub header_comment: Option<String>,
    /// CDR-only mode for the CORBA/GIOP path: omits the `DdsType` impl
    /// (XCDR2 + `field_value`) that pulls in `zerodds_dcps`/`zerodds_types`/
    /// `zerodds_sql_filter`. Only type declarations and classic
    /// `CdrEncode`/`CdrDecode` remain — the sole wire representation
    /// for CORBA requests/replies (CDR §15.3).
    pub cdr_only: bool,
}

/// Generates a single Rust module file from a parsed IDL spec.
///
/// # Errors
/// `Unsupported` for IDL constructs outside the DDS DataType scope.
pub fn generate_rust_module(spec: &Specification, opts: &RustGenOptions) -> Result<String> {
    // `any` target: cdr_only (CORBA path) → CorbaAny, otherwise DDS → DdsAny.
    crate::type_map::set_any_target_corba(opts.cdr_only);
    // This pass emits only data types, no interface references — clear the
    // interface-ref set (no stale state from a previous corba-rust run in
    // the same process, e.g. a two-pass build.rs).
    crate::type_map::set_interface_refs(core::iter::empty());
    // Record struct/enum/typedef names so `field_value` resolves scoped fields
    // (struct → forward, enum → int, typedef-to-primitive → leaf).
    crate::type_map::register_types_for_field_value(spec);
    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: Apache-2.0\n");
    if let Some(c) = &opts.header_comment {
        for line in c.lines() {
            out.push_str("// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("// Auto-generated by `zerodds-idl-rust`. Do not edit by hand.\n");
    out.push('\n');
    out.push_str("#![allow(clippy::too_many_lines)]\n");
    out.push_str("#![allow(unused_imports)]\n");
    // IDL identifiers may be camelCase (e.g. NGVA headlessCamelCase per
    // AEP-4754 Vol V §8.1.3); generated structs keep the IDL field spelling.
    out.push_str("#![allow(non_snake_case)]\n");
    out.push('\n');
    out.push_str("use zerodds_cdr::{BufferReader, BufferWriter, CdrDecode, CdrEncode, DecodeError, EncodeError, Endianness};\n");
    out.push('\n');

    let mut path: Vec<String> = Vec::new();
    for def in &spec.definitions {
        emit_definition(&mut out, def, &mut path, opts.cdr_only)?;
    }

    Ok(out)
}

/// Appends only the data-type definitions (struct/enum/union/exception/typedef/
/// bitset) from a spec to `out` — without a file header, `use` line, or
/// module wrapper. Used by the CORBA code generator (`zerodds-corba-rust`),
/// which emits types and interfaces into a shared module.
///
/// # Errors
/// `Unsupported` for IDL constructs outside the DataType scope.
pub fn append_data_types(out: &mut String, spec: &Specification, cdr_only: bool) -> Result<()> {
    crate::type_map::register_types_for_field_value(spec);
    let mut path: Vec<String> = Vec::new();
    for def in &spec.definitions {
        emit_definition(out, def, &mut path, cdr_only)?;
    }
    Ok(())
}

/// zerodds-lint: recursion-depth 16
/// IDL module nesting — 16 levels are sufficient for all known OMG spec IDL files.
fn emit_definition(
    out: &mut String,
    def: &Definition,
    path: &mut Vec<String>,
    cdr_only: bool,
) -> Result<()> {
    match def {
        Definition::Module(m) => emit_module(out, m, path, cdr_only),
        Definition::Type(t) => emit_type_decl(out, t, path, cdr_only),
        Definition::Except(e) => {
            emit_exception(out, e)?;
            out.push('\n');
            Ok(())
        }
        // Const is not emitted in the idl-rust path (compile-time
        // constants are language-specific; CORBA IDL Const is handled
        // in the language PSM).
        Definition::Const(_) => Ok(()),
        // Emit interface-nested exceptions as struct types — the CORBA
        // code generator (corba-rust) references them in the `{Iface}Error`
        // enum, and their RepositoryId carries the interface scope (e.g.
        // IDL:omg.org/CosNaming/NamingContext/NotFound:1.0). DDS IDL has no
        // interfaces, so this is a no-op in the DDS path.
        Definition::Interface(InterfaceDcl::Def(i)) => {
            for ex in &i.exports {
                if let Export::Except(e) = ex {
                    emit_exception(out, e)?;
                    out.push('\n');
                }
            }
            Ok(())
        }
        // Remaining CORBA/component declarations are not handled in the
        // Rust code generator (ZeroDDS Rust API is DDS-centric).
        _ => Ok(()),
    }
}

/// zerodds-lint: recursion-depth 16
fn emit_module(
    out: &mut String,
    m: &ModuleDef,
    path: &mut Vec<String>,
    cdr_only: bool,
) -> Result<()> {
    out.push_str("pub mod ");
    out.push_str(&escape_keyword(&m.name.text));
    out.push_str(" {\n");
    out.push_str("    use zerodds_cdr::{BufferReader, BufferWriter, CdrDecode, CdrEncode, DecodeError, EncodeError, Endianness};\n\n");
    // Push the raw IDL module name (not Rust-escaped) so TYPE_NAME
    // emits spec-conform `Module::Sub::Struct`. Conformance §3 / §5.
    path.push(m.name.text.clone());
    for inner in &m.definitions {
        let mut inner_out = String::new();
        emit_definition(&mut inner_out, inner, path, cdr_only)?;
        // Indent
        for line in inner_out.lines() {
            if line.is_empty() {
                out.push('\n');
            } else {
                out.push_str("    ");
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    path.pop();
    out.push_str("}\n\n");
    Ok(())
}

fn emit_type_decl(out: &mut String, td: &TypeDecl, path: &[String], cdr_only: bool) -> Result<()> {
    match td {
        TypeDecl::Constr(ConstrTypeDecl::Struct(struct_dcl)) => {
            // StructDcl is a wrapper around Def/Forward.
            use zerodds_idl::ast::types::StructDcl;
            match struct_dcl {
                StructDcl::Def(s) => {
                    crate::struct_emit::emit_struct_with_mode(out, s, path, cdr_only)?;
                    out.push('\n');
                }
                StructDcl::Forward(_) => {
                    // Forward declarations are not needed in Rust
                    // (order is handled via visibility/module).
                }
            }
        }
        TypeDecl::Constr(ConstrTypeDecl::Enum(e)) => {
            crate::enum_emit::emit_enum(out, e)?;
            out.push('\n');
        }
        TypeDecl::Constr(ConstrTypeDecl::Union(u)) => {
            use zerodds_idl::ast::types::UnionDcl;
            match u {
                UnionDcl::Def(def) => {
                    crate::union_emit::emit_union(out, def)?;
                    out.push('\n');
                }
                UnionDcl::Forward(_) => {}
            }
        }
        TypeDecl::Typedef(td) => {
            crate::typedef_emit::emit_typedef(out, td)?;
        }
        TypeDecl::Constr(ConstrTypeDecl::Bitset(b)) => {
            crate::bitset_emit::emit_bitset(out, b)?;
            out.push('\n');
        }
        TypeDecl::Constr(ConstrTypeDecl::Bitmask(m)) => {
            crate::bitset_emit::emit_bitmask(out, m)?;
            out.push('\n');
        }
        // `native X;` is an opaque, platform-specific type without a
        // DDS wire representation — not emitted in the DataType codegen
        // (analogous to `const`).
        TypeDecl::Native(_) => {}
    }
    Ok(())
}

/// Emits an IDL `exception` definition as a Rust struct + classic
/// `CdrEncode`/`CdrDecode` impls. CORBA exceptions are struct-like data
/// containers; on the wire they are marshalled like a struct
/// (CDR §15.3 — members in declaration order), embedded in the
/// `UserException` reply body (§15.4.2, behind the repository ID). The
/// generated interface code (`zerodds-corba-rust`) references them as an
/// error variant; the marshalling uses these impls.
fn emit_exception(out: &mut String, e: &ExceptDecl) -> Result<()> {
    use crate::struct_emit::{
        declarator_ident, emit_member_decode_let_with_reader, emit_member_encode_with_writer,
    };

    out.push_str("/// Generated by `zerodds-idl-rust` from IDL exception (CORBA 3.3 §7.4.10).\n");
    out.push_str("#[derive(Debug, Clone, PartialEq, Default)]\n");
    out.push_str("pub struct ");
    out.push_str(&escape_keyword(&e.name.text));
    out.push_str(" {\n");
    for member in &e.members {
        let rust_ty = rust_type_for(&member.type_spec)?;
        for declarator in &member.declarators {
            let raw = match declarator {
                Declarator::Simple(n) => &n.text,
                Declarator::Array(a) => &a.name.text,
            };
            let name = escape_keyword(raw);
            out.push_str(&format!("    pub {name}: {rust_ty},\n"));
        }
    }
    out.push_str("}\n");

    // CdrEncode — members sequential (classic CDR, no DHEADER).
    let name = escape_keyword(&e.name.text);
    out.push_str(&format!("\nimpl zerodds_cdr::CdrEncode for {name} {{\n"));
    out.push_str(
        "    fn encode(&self, writer: &mut zerodds_cdr::BufferWriter) -> ::core::result::Result<(), zerodds_cdr::EncodeError> {\n",
    );
    for member in &e.members {
        emit_member_encode_with_writer(out, member, "        ", "writer")?;
    }
    out.push_str("        ::core::result::Result::Ok(())\n");
    out.push_str("    }\n}\n");

    // CdrDecode — symmetric.
    out.push_str(&format!("\nimpl zerodds_cdr::CdrDecode for {name} {{\n"));
    out.push_str(
        "    fn decode(reader: &mut zerodds_cdr::BufferReader<'_>) -> ::core::result::Result<Self, zerodds_cdr::DecodeError> {\n",
    );
    for member in &e.members {
        emit_member_decode_let_with_reader(out, member, "        ", "reader")?;
    }
    out.push_str("        ::core::result::Result::Ok(Self {\n");
    for member in &e.members {
        for declarator in &member.declarators {
            let field = declarator_ident(declarator);
            out.push_str(&format!("            {field},\n"));
        }
    }
    out.push_str("        })\n");
    out.push_str("    }\n}\n");
    Ok(())
}
