// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Emittiert IDL `enum` → Rust `enum`.
//!
//! XTypes 1.3 §7.4.5.1 Enum-Wire-Format: 32-bit signed integer (`i32`)
//! with the value of the enumerator. Default mapping: 0..N-1 in
//! declaration order.

use zerodds_idl::ast::types::EnumDef;

use crate::annotations::enumerator_value;
use crate::error::Result;
use crate::type_map::escape_keyword;

/// Resolves the discriminant value of each enumerator, honoring an
/// explicit `@value(N)` annotation (XTypes 1.3 §7.3.1.2.1.6). Per the
/// spec, an enumerator without `@value` takes the previous enumerator's
/// value + 1, with the first defaulting to 0. The returned `i32` values
/// match the `#[repr(i32)]` wire encoding (§7.4.5.1) and MUST be the same
/// integers recorded into `ENUM_LITERAL_VALUES`, so a `union switch(EnumT)`
/// resolves its `case` labels identically.
fn enumerator_values(e: &EnumDef) -> Vec<i32> {
    let mut values = Vec::with_capacity(e.enumerators.len());
    let mut next: i128 = 0;
    for enumerator in &e.enumerators {
        let value = enumerator_value(&enumerator.annotations).unwrap_or(next);
        values.push(value as i32);
        next = value + 1;
    }
    values
}

/// Emittiert ein vollstaendiges Rust-Enum + DdsType-Impl.
pub fn emit_enum(out: &mut String, e: &EnumDef) -> Result<()> {
    let values = enumerator_values(e);
    out.push_str("/// Generated by `zerodds-idl-rust` from IDL enum.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("#[repr(i32)]\n");
    out.push_str("pub enum ");
    out.push_str(&escape_keyword(&e.name.text));
    out.push_str(" {\n");
    for (enumerator, value) in e.enumerators.iter().zip(&values) {
        out.push_str("    ");
        out.push_str(&escape_keyword(&enumerator.name.text));
        out.push_str(&format!(" = {value}"));
        out.push_str(",\n");
    }
    out.push_str("}\n\n");

    if let Some(first) = e.enumerators.first() {
        out.push_str("impl Default for ");
        out.push_str(&escape_keyword(&e.name.text));
        out.push_str(" {\n");
        out.push_str("    fn default() -> Self {\n");
        out.push_str(&format!(
            "        Self::{}\n",
            escape_keyword(&first.name.text)
        ));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    out.push_str("impl ");
    out.push_str(&escape_keyword(&e.name.text));
    out.push_str(" {\n");
    out.push_str("    /// Tries to map an `i32` wire value to an enumerator.\n");
    out.push_str("    #[must_use]\n");
    out.push_str("    pub fn from_wire(value: i32) -> Option<Self> {\n");
    out.push_str("        match value {\n");
    for (enumerator, value) in e.enumerators.iter().zip(&values) {
        out.push_str(&format!(
            "            {value} => Some(Self::{}),\n",
            escape_keyword(&enumerator.name.text)
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // CdrEncode/CdrDecode impls — the enum wire holder is a SIGNED integer
    // whose width is selected by `@bit_bound` (XTypes 1.3 §7.4.5.1 /
    // §7.3.1.2.1.2): bound≤8 → i8 (1 octet), ≤16 → i16 (2 octets), else i32.
    // The in-memory repr stays i32; only the wire cast narrows. Cyclone honours
    // this; the previous fixed-i32 path silently dropped `@bit_bound`.
    let octets =
        crate::annotations::enum_wire_octets(crate::annotations::enum_bit_bound(&e.annotations));
    let wire_ty = match octets {
        1 => "i8",
        2 => "i16",
        _ => "i32",
    };
    out.push_str("impl zerodds_cdr::CdrEncode for ");
    out.push_str(&escape_keyword(&e.name.text));
    out.push_str(" {\n");
    out.push_str("    fn encode(&self, w: &mut zerodds_cdr::BufferWriter) -> ::core::result::Result<(), zerodds_cdr::EncodeError> {\n");
    out.push_str(&format!(
        "        <{wire_ty} as zerodds_cdr::CdrEncode>::encode(&(*self as {wire_ty}), w)\n"
    ));
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("impl zerodds_cdr::CdrDecode for ");
    out.push_str(&escape_keyword(&e.name.text));
    out.push_str(" {\n");
    out.push_str("    fn decode(r: &mut zerodds_cdr::BufferReader<'_>) -> ::core::result::Result<Self, zerodds_cdr::DecodeError> {\n");
    if wire_ty == "i32" {
        out.push_str("        let v = <i32 as zerodds_cdr::CdrDecode>::decode(r)?;\n");
    } else {
        out.push_str(&format!(
            "        let v = i32::from(<{wire_ty} as zerodds_cdr::CdrDecode>::decode(r)?);\n"
        ));
    }
    out.push_str(&format!(
        "        Self::from_wire(v).ok_or(zerodds_cdr::DecodeError::InvalidEnum {{ kind: \"{}\", value: v as u32 }})\n",
        e.name.text
    ));
    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(())
}
