// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Emittiert `pub struct X { … }` plus `impl DdsType for X { … }`.
//!
//! Phase A: nur final-Extensibility, primitive Felder. Composite-Types
//! (String, Vec, Array, Option) folgen in Phase B; Extensibility-Modi
//! (appendable, mutable) in Phase C; Keys + KeyHash in Phase D.

use zerodds_idl::ast::types::{Declarator, Member, StructDef, TypeSpec};

use crate::annotations::{StructExtensibility, struct_extensibility};
use crate::error::{Result, RustGenError};
use crate::type_map::escape_keyword;
use crate::type_map::rust_type_for;

/// Returns the Rust identifier of a declarator as an owned `String`,
/// raw-identifier-escaped if needed (spec §6.1 + §6.2).
pub(crate) fn declarator_ident(decl: &Declarator) -> String {
    let raw = match decl {
        Declarator::Simple(n) => &n.text,
        Declarator::Array(a) => &a.name.text,
    };
    escape_keyword(raw)
}

/// Emits a complete Rust struct definition + DdsType impl.
///
/// `module_path` is the list of enclosing IDL modules (raw names). It is
/// used to emit the fully-qualified `TYPE_NAME` `"Module::Sub::Struct"`.
pub fn emit_struct(out: &mut String, s: &StructDef, module_path: &[String]) -> Result<()> {
    emit_struct_with_mode(out, s, module_path, false)
}

/// Like [`emit_struct`], but with a `cdr_only` switch: at `true` the
/// `DdsType` impl (XCDR2 + `field_value`, pulls `zerodds_dcps`/`zerodds_types`/
/// `zerodds_sql_filter`) is omitted. Only the struct decl + classic
/// `CdrEncode`/`CdrDecode` remain — exactly what the CORBA/GIOP path needs
/// (no DDS topic pipeline, hence no DdsType dependencies).
pub fn emit_struct_with_mode(
    out: &mut String,
    s: &StructDef,
    module_path: &[String],
    cdr_only: bool,
) -> Result<()> {
    let extensibility = struct_extensibility(&s.annotations);

    emit_struct_decl(out, s)?;
    out.push('\n');
    if !cdr_only {
        emit_dds_type_impl(out, s, extensibility, module_path)?;
    }
    // Writer-agnostic classic CDR impls (`CdrEncode`/`CdrDecode`). The
    // CORBA/GIOP codegen uses these with a non-`.xcdr2()` writer (classic
    // CDR §15.3); XCDR2/DDS stays in `DdsType::encode`. Also makes
    // nested-struct fields really resolvable via `<_ as CdrEncode>::encode`.
    emit_cdr_encode_impl(out, s)?;
    emit_cdr_decode_impl(out, s)?;
    Ok(())
}

/// `impl CdrEncode for <struct>` — plain sequential field encoding via the
/// passed `BufferWriter` (classic CDR; no XTypes DHEADER frames).
fn emit_cdr_encode_impl(out: &mut String, s: &StructDef) -> Result<()> {
    let name = escape_keyword(&s.name.text);
    out.push_str(&format!("\nimpl zerodds_cdr::CdrEncode for {name} {{\n"));
    out.push_str(
        "    fn encode(&self, writer: &mut zerodds_cdr::BufferWriter) -> ::core::result::Result<(), zerodds_cdr::EncodeError> {\n",
    );
    for member in &s.members {
        emit_member_encode_with_writer(out, member, "        ", "writer")?;
    }
    out.push_str("        ::core::result::Result::Ok(())\n");
    out.push_str("    }\n}\n");
    Ok(())
}

/// `impl CdrDecode for <struct>` — plain sequential field decoding from the
/// passed `BufferReader` (symmetric to [`emit_cdr_encode_impl`]).
fn emit_cdr_decode_impl(out: &mut String, s: &StructDef) -> Result<()> {
    let name = escape_keyword(&s.name.text);
    out.push_str(&format!("\nimpl zerodds_cdr::CdrDecode for {name} {{\n"));
    out.push_str(
        "    fn decode(reader: &mut zerodds_cdr::BufferReader<'_>) -> ::core::result::Result<Self, zerodds_cdr::DecodeError> {\n",
    );
    for member in &s.members {
        emit_member_decode_let_with_reader(out, member, "        ", "reader")?;
    }
    out.push_str("        ::core::result::Result::Ok(Self {\n");
    for member in &s.members {
        for declarator in &member.declarators {
            let field = declarator_ident(declarator);
            out.push_str(&format!("            {field},\n"));
        }
    }
    out.push_str("        })\n");
    out.push_str("    }\n}\n");
    Ok(())
}

fn emit_struct_decl(out: &mut String, s: &StructDef) -> Result<()> {
    out.push_str("/// Generated by `zerodds-idl-rust` from IDL.\n");
    out.push_str("#[derive(Debug, Clone, PartialEq, Default)]\n");
    out.push_str("pub struct ");
    out.push_str(&escape_keyword(&s.name.text));
    out.push_str(" {\n");
    for member in &s.members {
        emit_member_field(out, member)?;
    }
    out.push_str("}\n");
    Ok(())
}

fn emit_member_field(out: &mut String, member: &Member) -> Result<()> {
    let rust_ty = rust_type_for(&member.type_spec)?;
    let optional = crate::annotations::member_is_optional(&member.annotations);
    for declarator in &member.declarators {
        match declarator {
            Declarator::Simple(name) => {
                out.push_str("    pub ");
                out.push_str(&escape_keyword(&name.text));
                out.push_str(": ");
                if optional {
                    out.push_str(&format!("::core::option::Option<{rust_ty}>"));
                } else {
                    out.push_str(&rust_ty);
                }
                out.push_str(",\n");
            }
            Declarator::Array(arr) => {
                let mut wrapped = rust_ty.clone();
                for size_expr in arr.sizes.iter().rev() {
                    let size = crate::type_map::const_expr_as_usize(size_expr).ok_or(
                        RustGenError::InvalidAnnotation {
                            name: "array-size".to_string(),
                            reason: "non-integer array dimension",
                        },
                    )?;
                    wrapped = format!("[{wrapped}; {size}]");
                }
                out.push_str("    pub ");
                out.push_str(&escape_keyword(&arr.name.text));
                out.push_str(": ");
                if optional {
                    out.push_str(&format!("::core::option::Option<{wrapped}>"));
                } else {
                    out.push_str(&wrapped);
                }
                out.push_str(",\n");
            }
        }
    }
    Ok(())
}

fn emit_dds_type_impl(
    out: &mut String,
    s: &StructDef,
    extensibility: StructExtensibility,
    module_path: &[String],
) -> Result<()> {
    let key_members: Vec<&Member> = s
        .members
        .iter()
        .filter(|m| crate::annotations::member_is_key(&m.annotations))
        .collect();
    let has_key = !key_members.is_empty();
    let key_holder_max_size = compute_key_holder_max_size(&key_members);

    out.push_str("impl zerodds_dcps::DdsType for ");
    out.push_str(&escape_keyword(&s.name.text));
    out.push_str(" {\n");
    // TYPE_NAME is the fully qualified IDL scoped name
    // (`Module::Sub::Struct`). Spec: zerodds-xcdr2-bindings-conformance
    // §3 / §5 + V-7 in conjunction with XTypes 1.3 §7.3.4.6. Strictly the
    // OMG IDL format with a `::` separator, NOT Rust syntax.
    out.push_str("    const TYPE_NAME: &'static str = \"");
    for module in module_path {
        out.push_str(module);
        out.push_str("::");
    }
    out.push_str(&s.name.text);
    out.push_str("\";\n");
    // EXTENSIBILITY-Const (zerodds-xcdr2-rust §2.3 + §6).
    let ext_variant = match extensibility {
        StructExtensibility::Final => "Final",
        StructExtensibility::Appendable => "Appendable",
        StructExtensibility::Mutable => "Mutable",
    };
    out.push_str(&format!(
        "    const EXTENSIBILITY: zerodds_dcps::Extensibility = zerodds_dcps::Extensibility::{ext_variant};\n"
    ));
    if has_key {
        out.push_str("    const HAS_KEY: bool = true;\n");
        if let Some(size) = key_holder_max_size {
            out.push_str(&format!(
                "    const KEY_HOLDER_MAX_SIZE: ::core::option::Option<usize> = ::core::option::Option::Some({size});\n"
            ));
        }
    }
    if crate::annotations::struct_is_nested(&s.annotations) {
        out.push_str("    const IS_NESTED: bool = true;\n");
    }
    // F-TYPES-3: TYPE_IDENTIFIER (XTypes 1.3 §7.3.4.2) as a const.
    // Codegen-time-computed EquivalenceHash of the `CompleteStructType`,
    // if all member types are leaf-resolvable; otherwise `None`.
    let type_id_expr = crate::type_identifier::struct_type_identifier_expr(s);
    out.push_str(&format!(
        "    const TYPE_IDENTIFIER: zerodds_types::TypeIdentifier = {type_id_expr};\n"
    ));
    out.push('\n');

    // encode
    out.push_str("    fn encode(&self, out: &mut ::std::vec::Vec<u8>) -> ::core::result::Result<(), zerodds_dcps::EncodeError> {\n");
    out.push_str(
        "        let mut writer = zerodds_cdr::BufferWriter::new(zerodds_cdr::Endianness::Little).xcdr2();\n",
    );
    emit_encode_body(out, s, extensibility)?;
    out.push_str("        out.extend_from_slice(&writer.into_bytes());\n");
    out.push_str("        Ok(())\n");
    out.push_str("    }\n\n");

    // decode
    out.push_str(
        "    fn decode(bytes: &[u8]) -> ::core::result::Result<Self, zerodds_dcps::DecodeError> {\n",
    );
    out.push_str("        let mut reader = zerodds_cdr::BufferReader::new(bytes, zerodds_cdr::Endianness::Little).xcdr2();\n");
    emit_decode_body(out, s, extensibility)?;
    out.push_str("    }\n");

    if has_key {
        out.push('\n');
        emit_key_holder_be(out, &key_members)?;
    }

    out.push('\n');
    emit_field_value(out, s)?;

    out.push_str("}\n");
    Ok(())
}

/// Emittiert `fn field_value(&self, path: &str) -> Option<zerodds_sql_filter::Value>`
/// for SQL-filter evaluation (QueryCondition / ContentFilteredTopic).
///
/// DDS 1.4 §B.2.1: filter expressions reference field values via
/// dotted paths (e.g. `"sensor.id"`). Rust DataTypes implement this here
/// as a deterministic match-arm table.
fn emit_field_value(out: &mut String, s: &StructDef) -> Result<()> {
    out.push_str(
        "    fn field_value(&self, path: &str) -> ::core::option::Option<zerodds_sql_filter::Value> {\n",
    );
    out.push_str("        match path {\n");
    for member in &s.members {
        let optional = crate::annotations::member_is_optional(&member.annotations);
        for declarator in &member.declarators {
            let name = declarator_ident(declarator);
            emit_field_value_arm(out, &member.type_spec, &name, declarator, optional)?;
        }
    }
    out.push_str("            _ => ::core::option::Option::None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    Ok(())
}

fn emit_field_value_arm(
    out: &mut String,
    spec: &TypeSpec,
    name: &str,
    declarator: &Declarator,
    optional: bool,
) -> Result<()> {
    use zerodds_idl::ast::types::{FloatingType, PrimitiveType};

    // Array fields cannot be mapped directly to Value — filter
    // expressions reference element indices (`"arr[0]"`), which is
    // outside the current RC1 scope. We emit nothing and the `_`
    // fallback kicks in.
    if matches!(declarator, Declarator::Array(_)) {
        return Ok(());
    }

    // Optional-Pattern:
    //     self.x.as_ref().map(|v| Value::Int(*v as i64))
    // Non-Optional:
    //     ::core::option::Option::Some(Value::Int(self.x as i64))
    let value_expr: Option<String> = match spec {
        TypeSpec::Primitive(
            PrimitiveType::Integer(_)
            | PrimitiveType::Octet
            | PrimitiveType::Char
            | PrimitiveType::WideChar,
        ) => Some(if optional {
            format!("self.{name}.as_ref().map(|v| zerodds_sql_filter::Value::Int(*v as i64))")
        } else {
            format!(
                "::core::option::Option::Some(zerodds_sql_filter::Value::Int(self.{name} as i64))"
            )
        }),
        TypeSpec::Primitive(PrimitiveType::Floating(FloatingType::Float)) => Some(if optional {
            format!("self.{name}.as_ref().map(|v| zerodds_sql_filter::Value::Float(*v as f64))")
        } else {
            format!(
                "::core::option::Option::Some(zerodds_sql_filter::Value::Float(self.{name} as f64))"
            )
        }),
        TypeSpec::Primitive(PrimitiveType::Floating(_)) => Some(if optional {
            format!("self.{name}.as_ref().map(|v| zerodds_sql_filter::Value::Float(*v))")
        } else {
            format!("::core::option::Option::Some(zerodds_sql_filter::Value::Float(self.{name}))")
        }),
        TypeSpec::Primitive(PrimitiveType::Boolean) => Some(if optional {
            format!("self.{name}.as_ref().map(|v| zerodds_sql_filter::Value::Bool(*v))")
        } else {
            format!("::core::option::Option::Some(zerodds_sql_filter::Value::Bool(self.{name}))")
        }),
        TypeSpec::String(_) => Some(if optional {
            format!("self.{name}.as_ref().map(|v| zerodds_sql_filter::Value::String(v.clone()))")
        } else {
            format!(
                "::core::option::Option::Some(zerodds_sql_filter::Value::String(self.{name}.clone()))"
            )
        }),
        TypeSpec::Scoped(_) => {
            // Nested struct/enum: dotted-path forwarding. We emit a
            // pattern that matches `name.<rest>` and forwards to
            // `self.<name>.field_value(rest)`.
            //
            // Special case: enums are converted via `i32::from(self.<name>)`
            // — which is not trivial in codegen without a type lookup. For
            // RC1 we leave enums to the caller's `_` fallback. Phase 2
            // extends this with a type index.
            out.push_str(&format!(
                "            p if p.starts_with(\"{name}.\") => self.{name}.field_value(&p[\"{name}.\".len()..]),\n"
            ));
            None
        }
        // Sequence / array / optional: no direct value conversion.
        TypeSpec::Sequence(_) | TypeSpec::Fixed(_) | TypeSpec::Map(_) | TypeSpec::Any => None,
    };

    if let Some(expr) = value_expr {
        out.push_str(&format!("            \"{name}\" => {expr},\n"));
    }
    Ok(())
}

/// Computes the `KEY_HOLDER_MAX_SIZE` value: the sum of the wire sizes
/// of all `@key` members, if all are fixed-size. For string/sequence/etc.
/// `None` is returned (MD5 path in `compute_key_hash`).
fn compute_key_holder_max_size(key_members: &[&Member]) -> Option<usize> {
    let mut total = 0usize;
    for member in key_members {
        let size = crate::type_map::wire_size_bound(&member.type_spec)?;
        for declarator in &member.declarators {
            let count = match declarator {
                Declarator::Simple(_) => 1,
                Declarator::Array(arr) => {
                    let mut n = 1usize;
                    for size_expr in &arr.sizes {
                        let dim = crate::type_map::const_expr_as_usize(size_expr)?;
                        n = n.checked_mul(dim)?;
                    }
                    n
                }
            };
            total = total.checked_add(size.checked_mul(count)?)?;
        }
    }
    Some(total)
}

fn emit_key_holder_be(out: &mut String, key_members: &[&Member]) -> Result<()> {
    out.push_str(
        "    fn encode_key_holder_be(&self, holder: &mut zerodds_cdr::PlainCdr2BeKeyHolder) {\n",
    );
    // Spec: XTypes 1.3 §7.6.8.3.1.b — members sorted in member-id order.
    // We use the positional IDs of the decl order as the default. With
    // `@id(N)`, N is used instead.
    let mut ordered: Vec<(u32, &Member)> = key_members
        .iter()
        .enumerate()
        .map(|(idx, m)| {
            (
                crate::annotations::member_id(&m.annotations).unwrap_or(idx as u32),
                *m,
            )
        })
        .collect();
    ordered.sort_by_key(|(id, _)| *id);
    for (_, member) in &ordered {
        for declarator in &member.declarators {
            let name = declarator_ident(declarator);
            emit_key_field_write(out, &member.type_spec, &format!("self.{name}"))?;
        }
    }
    out.push_str("    }\n");
    Ok(())
}

fn emit_key_field_write(out: &mut String, spec: &TypeSpec, value_expr: &str) -> Result<()> {
    use zerodds_idl::ast::types::{FloatingType, IntegerType, PrimitiveType};
    match spec {
        TypeSpec::Primitive(p) => {
            let method = match p {
                PrimitiveType::Integer(IntegerType::Int8) => "write_i8",
                PrimitiveType::Integer(IntegerType::UInt8) | PrimitiveType::Octet => "write_u8",
                PrimitiveType::Integer(IntegerType::Short | IntegerType::Int16) => "write_i16",
                PrimitiveType::Integer(IntegerType::UShort | IntegerType::UInt16) => "write_u16",
                PrimitiveType::Integer(IntegerType::Long | IntegerType::Int32) => "write_i32",
                PrimitiveType::Integer(IntegerType::ULong | IntegerType::UInt32) => "write_u32",
                PrimitiveType::Integer(IntegerType::LongLong | IntegerType::Int64) => "write_i64",
                PrimitiveType::Integer(IntegerType::ULongLong | IntegerType::UInt64) => "write_u64",
                PrimitiveType::Floating(FloatingType::Float) => "write_f32",
                PrimitiveType::Floating(FloatingType::Double | FloatingType::LongDouble) => {
                    "write_f64"
                }
                PrimitiveType::Boolean => "write_u8",
                PrimitiveType::Char => "write_u8",
                PrimitiveType::WideChar => "write_u16",
            };
            if matches!(
                p,
                PrimitiveType::Char | PrimitiveType::WideChar | PrimitiveType::Boolean
            ) {
                out.push_str(&format!("        holder.{method}({value_expr} as _);\n"));
            } else {
                out.push_str(&format!("        holder.{method}({value_expr});\n"));
            }
        }
        TypeSpec::String(_) => {
            // PlainCdr2BeKeyHolder has a `write_string` method that
            // inserts the UTF-8 bytes directly (spec §7.6.8.4 — strings
            // carry their length prefix in big-endian).
            out.push_str(&format!("        holder.write_string(&{value_expr});\n"));
        }
        TypeSpec::Sequence(_) | TypeSpec::Scoped(_) => {
            return Err(RustGenError::Unsupported {
                what: "complex @key field (sequence or nested struct)",
                at: 0,
            });
        }
        TypeSpec::Fixed(f) => {
            return Err(RustGenError::Unsupported {
                what: "fixed @key",
                at: f.span.start,
            });
        }
        TypeSpec::Map(m) => {
            return Err(RustGenError::Unsupported {
                what: "map @key",
                at: m.span.start,
            });
        }
        TypeSpec::Any => {
            return Err(RustGenError::Unsupported {
                what: "any @key",
                at: 0,
            });
        }
    }
    Ok(())
}

fn emit_encode_body(
    out: &mut String,
    s: &StructDef,
    extensibility: StructExtensibility,
) -> Result<()> {
    match extensibility {
        StructExtensibility::Final => {
            for member in &s.members {
                emit_member_encode(out, member, "        ")?;
            }
        }
        StructExtensibility::Appendable => {
            // Phase C: zerodds_cdr::struct_enc::encode_appendable
            out.push_str("        zerodds_cdr::struct_enc::encode_appendable(&mut writer, |w| {\n");
            for member in &s.members {
                emit_member_encode_with_writer(out, member, "            ", "w")?;
            }
            out.push_str("            Ok(())\n");
            out.push_str("        })?;\n");
        }
        StructExtensibility::Mutable => {
            // XTypes 1.3 §7.4.3.4.4: @mutable structs MUST be wrapped
            // in a DHEADER frame so nested-mutable readers can skip-by-
            // length when they encounter unknown member-ids. The
            // decode side already uses `decode_appendable` to strip
            // the DHEADER, so the encode side must symmetric-wrap.
            // Spec anchor: zerodds-xcdr2-bindings-conformance §6 V-10
            // (`14 00 00 00` DHEADER + member list).
            let required_ids: Vec<u32> = s
                .members
                .iter()
                .enumerate()
                .filter(|(_, m)| !crate::annotations::member_is_optional(&m.annotations))
                .map(|(idx, m)| crate::annotations::member_id(&m.annotations).unwrap_or(idx as u32))
                .collect();
            let required_list = required_ids
                .iter()
                .map(|id| id.to_string())
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str("        zerodds_cdr::struct_enc::encode_appendable(&mut writer, |w| {\n");
            out.push_str(&format!(
                "            let mut enc = zerodds_cdr::struct_enc::MutableStructEncoder::new(w, ::std::vec![{required_list}]);\n"
            ));
            for (idx, member) in s.members.iter().enumerate() {
                emit_mutable_member_encode(out, member, idx, "            ")?;
            }
            out.push_str("            enc.finish()?;\n");
            out.push_str("            Ok(())\n");
            out.push_str("        })?;\n");
        }
    }
    Ok(())
}

fn emit_member_encode(out: &mut String, member: &Member, indent: &str) -> Result<()> {
    emit_member_encode_with_writer(out, member, indent, "&mut writer")
}

pub(crate) fn emit_member_encode_with_writer(
    out: &mut String,
    member: &Member,
    indent: &str,
    writer_expr: &str,
) -> Result<()> {
    for declarator in &member.declarators {
        let name = declarator_ident(declarator);
        out.push_str(indent);
        emit_member_bound_checks(out, member, declarator);
        emit_field_encode(out, &member.type_spec, &format!("self.{name}"), writer_expr)?;
        out.push('\n');
    }
    Ok(())
}

/// Emits a `zerodds_cdr::CdrEncode::encode` call for a field.
///
/// **Uniform trait API** — all primitives + composite types
/// (String, Vec, [T;N], Option) have `impl CdrEncode` in
/// `zerodds_cdr::encode` / `zerodds_cdr::composite`. The codegen thus
/// need not distinguish between primitive method calls and function
/// calls.
pub fn emit_field_encode(
    out: &mut String,
    spec: &TypeSpec,
    value_expr: &str,
    writer_expr: &str,
) -> Result<()> {
    let _ = spec;
    // Uniform trait path for primitives + composite + scoped + Fixed +
    // Map + Any (all have CdrEncode impls). Bound enforcement
    // (DDS-XTypes §7.4.3) runs separately at the declarator level via
    // `emit_member_bound_checks` — there it is known whether the field is
    // an array (otherwise `value_expr.len()` would wrongly check the
    // array length instead of the sequence length).
    out.push_str(&format!(
        "<_ as zerodds_cdr::CdrEncode>::encode(&{value_expr}, {writer_expr})?;"
    ));
    Ok(())
}

/// `true` if `spec` itself is a bounded sequence/string with a known
/// (const-evaluable) bound — or recursively contains one (through
/// sequence nesting). Structs/scoped types do NOT count: their own
/// `CdrEncode` impl enforces their field bounds themselves once the
/// element is encoded. Controls whether `emit_bound_checks` emits loops.
fn bound_is_known(bound: &Option<zerodds_idl::ast::types::ConstExpr>) -> bool {
    bound
        .as_ref()
        .and_then(crate::type_map::const_expr_as_usize)
        .is_some()
}

/// zerodds-lint: recursion-depth 64 (bounded by IDL nesting)
fn type_has_bounds(spec: &TypeSpec) -> bool {
    match spec {
        TypeSpec::Sequence(seq) => bound_is_known(&seq.bound) || type_has_bounds(&seq.elem),
        // narrow `string<N>` AND wide `wstring<N>` are both enforced now.
        TypeSpec::String(s) => bound_is_known(&s.bound),
        TypeSpec::Map(m) => {
            bound_is_known(&m.bound) || type_has_bounds(&m.value) || type_has_bounds(&m.key)
        }
        _ => false,
    }
}

/// Emits recursive bound checks (DDS-XTypes §7.4.3) for `value_expr` of
/// type `spec`: a bounded `sequence<T,N>` / `string<N>` / `wstring<N>` /
/// `map<K,V,N>` longer than `N` is an ENCODE error
/// (`EncodeError::ValueOutOfRange`) — strict vendors (OpenDDS) reject it
/// on the wire. Descends through sequence/map nesting
/// (`sequence<sequence<octet,4>>` checks both levels, `map<string,seq<T,4>,8>`
/// checks the map bound + each value). `depth` makes the loop variables unique.
///
/// zerodds-lint: recursion-depth 64 (bounded by IDL nesting)
fn emit_bound_checks(out: &mut String, spec: &TypeSpec, value_expr: &str, depth: usize) {
    match spec {
        TypeSpec::Sequence(seq) => {
            if let Some(n) = seq
                .bound
                .as_ref()
                .and_then(crate::type_map::const_expr_as_usize)
            {
                out.push_str(&format!(
                    "if {value_expr}.len() > {n} {{ return Err(zerodds_cdr::EncodeError::ValueOutOfRange {{ message: \"bounded sequence length exceeds its IDL bound ({n})\" }}); }} "
                ));
            }
            if type_has_bounds(&seq.elem) {
                let item = format!("__b{depth}");
                out.push_str(&format!("for {item} in {value_expr}.iter() {{ "));
                emit_bound_checks(out, &seq.elem, &item, depth + 1);
                out.push_str("} ");
            }
        }
        TypeSpec::String(s) => {
            if let Some(n) = s
                .bound
                .as_ref()
                .and_then(crate::type_map::const_expr_as_usize)
            {
                if s.wide {
                    // `wstring<N>`: bound is in wide characters = UTF-16 code
                    // units (GIOP 1.2 §15.3.2.7 encodes UTF-16). `WString`
                    // wraps a `String`; count its UTF-16 units.
                    out.push_str(&format!(
                        "if {value_expr}.as_str().encode_utf16().count() > {n} {{ return Err(zerodds_cdr::EncodeError::ValueOutOfRange {{ message: \"bounded wstring length exceeds its IDL bound ({n})\" }}); }} "
                    ));
                } else {
                    // narrow `string<N>`: CDR encodes byte-wise (`as_bytes`),
                    // so the bound guards the UTF-8 byte length (ASCII = chars).
                    out.push_str(&format!(
                        "if {value_expr}.len() > {n} {{ return Err(zerodds_cdr::EncodeError::ValueOutOfRange {{ message: \"bounded string length exceeds its IDL bound ({n})\" }}); }} "
                    ));
                }
            }
        }
        TypeSpec::Map(m) => {
            if let Some(n) = m
                .bound
                .as_ref()
                .and_then(crate::type_map::const_expr_as_usize)
            {
                out.push_str(&format!(
                    "if {value_expr}.len() > {n} {{ return Err(zerodds_cdr::EncodeError::ValueOutOfRange {{ message: \"bounded map length exceeds its IDL bound ({n})\" }}); }} "
                ));
            }
            // Recurse into bounded map values + keys (`map<string<4>, seq<T,8>>`).
            if type_has_bounds(&m.value) {
                let item = format!("__b{depth}");
                out.push_str(&format!("for {item} in {value_expr}.values() {{ "));
                emit_bound_checks(out, &m.value, &item, depth + 1);
                out.push_str("} ");
            }
            if type_has_bounds(&m.key) {
                let item = format!("__k{depth}");
                out.push_str(&format!("for {item} in {value_expr}.keys() {{ "));
                emit_bound_checks(out, &m.key, &item, depth + 1);
                out.push_str("} ");
            }
        }
        _ => {}
    }
}

/// Emits bound checks for a value `base_expr` of declared type
/// `type_spec` with `declarator`. For an array declarator
/// (`sequence<octet,4> arr[3]`) `base_expr` is a (possibly
/// multidimensional) array of the element type — it iterates over all
/// array elements so the array length is not wrongly checked against the
/// sequence bound. Shared by struct members (`base = self.{name}`) and
/// union arms (`base = __v`).
pub(crate) fn emit_bound_checks_decl(
    out: &mut String,
    type_spec: &TypeSpec,
    declarator: &Declarator,
    base_expr: &str,
) {
    if !type_has_bounds(type_spec) {
        return;
    }
    match declarator {
        Declarator::Simple(_) => emit_bound_checks(out, type_spec, base_expr, 0),
        Declarator::Array(arr) => {
            let mut expr = base_expr.to_string();
            for (i, _) in arr.sizes.iter().enumerate() {
                let item = format!("__a{i}");
                out.push_str(&format!("for {item} in {expr}.iter() {{ "));
                expr = item;
            }
            emit_bound_checks(out, type_spec, &expr, 0);
            for _ in &arr.sizes {
                out.push_str("} ");
            }
        }
    }
}

fn emit_member_bound_checks(out: &mut String, member: &Member, declarator: &Declarator) {
    let base = format!("self.{}", declarator_ident(declarator));
    emit_bound_checks_decl(out, &member.type_spec, declarator, &base);
}

fn emit_mutable_member_encode(
    out: &mut String,
    member: &Member,
    fallback_id: usize,
    indent: &str,
) -> Result<()> {
    let id = crate::annotations::member_id(&member.annotations).unwrap_or(fallback_id as u32);
    let must_understand = crate::annotations::member_must_understand(&member.annotations);
    for declarator in &member.declarators {
        let name = declarator_ident(declarator);
        out.push_str(indent);
        out.push_str(&format!(
            "enc.encode_member({id}, {must_understand}, |w| {{ "
        ));
        emit_member_bound_checks(out, member, declarator);
        emit_field_encode(out, &member.type_spec, &format!("self.{name}"), "w")?;
        out.push_str(" Ok(()) })?;\n");
    }
    Ok(())
}

fn emit_decode_body(
    out: &mut String,
    s: &StructDef,
    extensibility: StructExtensibility,
) -> Result<()> {
    match extensibility {
        StructExtensibility::Final => {
            // Decode in declaration order.
            for member in &s.members {
                emit_member_decode_let(out, member, "        ")?;
            }
            out.push_str("        Ok(Self {\n");
            for member in &s.members {
                for declarator in &member.declarators {
                    let name = declarator_ident(declarator);
                    out.push_str(&format!("            {name},\n"));
                }
            }
            out.push_str("        })\n");
        }
        StructExtensibility::Appendable => {
            out.push_str("        zerodds_cdr::struct_enc::decode_appendable(&mut reader, |r| {\n");
            for member in &s.members {
                emit_member_decode_let_with_reader(out, member, "            ", "r")?;
            }
            out.push_str("            Ok(Self {\n");
            for member in &s.members {
                for declarator in &member.declarators {
                    let name = declarator_ident(declarator);
                    out.push_str(&format!("                {name},\n"));
                }
            }
            out.push_str("            })\n");
            out.push_str("        }).map_err(::core::convert::Into::into)\n");
        }
        StructExtensibility::Mutable => {
            // XTypes 1.3 §7.4.3.4.4: mutable decode with arbitrary
            // member order via the read_mutable_member loop +
            // member-id match. We track an Option<T> per member;
            // unknown must_understand member IDs lead to a decode error.
            out.push_str("        zerodds_cdr::struct_enc::decode_appendable(&mut reader, |r| {\n");
            // Pre-init all member slots as Option<T>::None.
            for (idx, member) in s.members.iter().enumerate() {
                let id = crate::annotations::member_id(&member.annotations).unwrap_or(idx as u32);
                let optional = crate::annotations::member_is_optional(&member.annotations);
                let base_type = rust_type_for(&member.type_spec)?;
                let target = if optional {
                    format!("::core::option::Option<{base_type}>")
                } else {
                    base_type
                };
                for declarator in &member.declarators {
                    let name = declarator_ident(declarator);
                    out.push_str(&format!(
                        "            // member-id {id}\n            let mut {name}: ::core::option::Option<{target}> = ::core::option::Option::None;\n"
                    ));
                }
            }
            // Loop over all mutable members on the wire.
            out.push_str("            loop {\n");
            out.push_str(
                "                match zerodds_cdr::struct_enc::read_mutable_member(r)? {\n",
            );
            out.push_str("                    ::core::option::Option::Some(member) => {\n");
            out.push_str("                        let mut body_reader = zerodds_cdr::BufferReader::new(member.body, zerodds_cdr::Endianness::Little).xcdr2();\n");
            out.push_str("                        match member.member_id {\n");
            for (idx, member) in s.members.iter().enumerate() {
                let id = crate::annotations::member_id(&member.annotations).unwrap_or(idx as u32);
                let optional = crate::annotations::member_is_optional(&member.annotations);
                for declarator in &member.declarators {
                    let name = declarator_ident(declarator);
                    out.push_str(&format!("                            {id} => {{\n"));
                    out.push_str(&format!(
                        "                                {name} = ::core::option::Option::Some("
                    ));
                    emit_field_decode_with_optional(
                        out,
                        &member.type_spec,
                        "&mut body_reader",
                        optional,
                    )?;
                    out.push_str(");\n");
                    out.push_str("                            }\n");
                }
            }
            out.push_str("                            _ => {\n");
            out.push_str("                                if member.must_understand {\n");
            out.push_str("                                    return ::core::result::Result::Err(zerodds_cdr::DecodeError::UnknownMustUnderstandMember {\n");
            out.push_str("                                        member_id: member.member_id,\n");
            out.push_str("                                    });\n");
            out.push_str("                                }\n");
            out.push_str("                                // unknown optional member: skip body\n");
            out.push_str("                            }\n");
            out.push_str("                        }\n");
            out.push_str("                    }\n");
            out.push_str("                    ::core::option::Option::None => break,\n");
            out.push_str("                }\n");
            out.push_str("            }\n");
            // Self-init with ok_or for mandatory members, or unwrap_or_default for optionals.
            out.push_str("            ::core::result::Result::Ok(Self {\n");
            for (idx, member) in s.members.iter().enumerate() {
                let id = crate::annotations::member_id(&member.annotations).unwrap_or(idx as u32);
                let optional = crate::annotations::member_is_optional(&member.annotations);
                for declarator in &member.declarators {
                    let name = declarator_ident(declarator);
                    if optional {
                        out.push_str(&format!(
                            "                {name}: {name}.unwrap_or(::core::option::Option::None),\n"
                        ));
                    } else {
                        out.push_str(&format!(
                            "                {name}: {name}.ok_or(zerodds_cdr::DecodeError::MissingNonOptionalMember {{ member_id: {id} }})?,\n"
                        ));
                    }
                }
            }
            out.push_str("            })\n");
            out.push_str("        }).map_err(::core::convert::Into::into)\n");
        }
    }
    Ok(())
}

fn emit_member_decode_let(out: &mut String, member: &Member, indent: &str) -> Result<()> {
    emit_member_decode_let_with_reader(out, member, indent, "&mut reader")
}

pub(crate) fn emit_member_decode_let_with_reader(
    out: &mut String,
    member: &Member,
    indent: &str,
    reader_expr: &str,
) -> Result<()> {
    let optional = crate::annotations::member_is_optional(&member.annotations);
    for declarator in &member.declarators {
        let name = declarator_ident(declarator);
        out.push_str(indent);
        out.push_str(&format!("let {name} = "));
        emit_field_decode_with_optional(out, &member.type_spec, reader_expr, optional)?;
        out.push_str(";\n");
    }
    Ok(())
}

/// Emits a `zerodds_cdr::CdrDecode::decode` call that reads a value of
/// type `target_type` from the reader.
///
/// We use the **fully-qualified trait form** with an explicit target
/// type so that type inference works even with `let x = ...;` without a
/// right-hand side.
fn emit_field_decode_with_optional(
    out: &mut String,
    spec: &TypeSpec,
    reader_expr: &str,
    optional: bool,
) -> Result<()> {
    let target = rust_type_for(spec)?;
    let final_target = if optional {
        format!("::core::option::Option<{target}>")
    } else {
        target
    };
    out.push_str(&format!(
        "<{final_target} as zerodds_cdr::CdrDecode>::decode({reader_expr})?"
    ));
    Ok(())
}
