// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Emits IDL `union` → Rust `enum` with a discriminator.
//!
//! XTypes 1.3 §7.4.1.4.5 union wire format:
//!
//! ```text
//! discriminator-value : <switch-type>
//! variant-body         : <case-type>
//! ```
//!
//! Rust mapping: tagged enum with a `repr` of the switch type. Variants
//! carry the respective case-body struct.

use zerodds_idl::ast::types::{Case, ConstExpr, Declarator, SwitchTypeSpec, TypeSpec, UnionDef};

use crate::error::{Result, RustGenError};
use crate::type_map::escape_keyword;
use crate::type_map::rust_type_for;

/// Emits a Rust enum representation of an IDL union.
pub fn emit_union(out: &mut String, u: &UnionDef) -> Result<()> {
    out.push_str("/// Generated by `zerodds-idl-rust` from IDL union.\n");
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub enum ");
    out.push_str(&escape_keyword(&u.name.text));
    out.push_str(" {\n");
    for case in &u.cases {
        emit_case_variant(out, case)?;
    }
    out.push_str("}\n\n");

    // Default impl: first variant
    if let Some(first) = u.cases.first() {
        let variant_name = &first.element.declarator.name().text;
        out.push_str("impl Default for ");
        out.push_str(&escape_keyword(&u.name.text));
        out.push_str(" {\n");
        out.push_str("    fn default() -> Self {\n");
        // Default value of the first variant
        let elem_type = rust_type_for(&first.element.type_spec)?;
        out.push_str(&format!(
            "        Self::{} (<{}>::default())\n",
            capitalize(variant_name),
            elem_type
        ));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    // CDR wire (classic + writer-agnostic): discriminator (switch-type)
    // followed by the active member. CORBA §15.3.2.6 / XTypes §7.4.1.4.5.
    // The CORBA codegen uses this with a classic (non-.xcdr2()) writer.
    let switch_ty = switch_repr(&u.switch_type)?;
    let cases = gather_union_cases(u)?;
    emit_union_cdr_encode(out, u, &cases, switch_ty);
    emit_union_cdr_decode(out, u, &cases, switch_ty);
    Ok(())
}

/// Pro Case aufbereitete Wire-Infos.
struct UnionCase {
    variant: String,
    elem_type: String,
    value_labels: Vec<i128>,
    is_default: bool,
    /// Declared type + declarator of the arm body — for bounded-collection
    /// enforcement (DDS-XTypes §7.4.3) on the active member at encode time.
    type_spec: TypeSpec,
    declarator: Declarator,
}

/// Evaluates the `case <expr>:` labels to i128 + collects variant/type per case.
fn gather_union_cases(u: &UnionDef) -> Result<Vec<UnionCase>> {
    use zerodds_idl::ast::types::CaseLabel;
    let mut out = Vec::with_capacity(u.cases.len());
    for case in &u.cases {
        let mut value_labels = Vec::new();
        let mut is_default = false;
        for label in &case.labels {
            match label {
                CaseLabel::Value(expr) => {
                    let v = const_label_as_i128(expr).ok_or(RustGenError::Unsupported {
                        what: "union case label (only integer-literal labels supported)",
                        at: 0,
                    })?;
                    value_labels.push(v);
                }
                CaseLabel::Default => is_default = true,
            }
        }
        out.push(UnionCase {
            variant: capitalize(&case.element.declarator.name().text),
            elem_type: rust_type_for(&case.element.type_spec)?,
            value_labels,
            is_default,
            type_spec: case.element.type_spec.clone(),
            declarator: case.element.declarator.clone(),
        });
    }
    Ok(out)
}

/// Discriminator value for the default arm: the smallest non-negative i128 that
/// matches no explicit label (roundtrip-stable, since both sides know the same
/// union definition).
fn default_discriminator(cases: &[UnionCase]) -> i128 {
    let used: std::collections::BTreeSet<i128> = cases
        .iter()
        .flat_map(|c| c.value_labels.iter().copied())
        .collect();
    let mut d = 0i128;
    while used.contains(&d) {
        d += 1;
    }
    d
}

fn emit_union_cdr_encode(out: &mut String, u: &UnionDef, cases: &[UnionCase], switch_ty: &str) {
    let name = escape_keyword(&u.name.text);
    let dd = default_discriminator(cases);
    out.push_str(&format!("\nimpl zerodds_cdr::CdrEncode for {name} {{\n"));
    out.push_str("    fn encode(&self, writer: &mut zerodds_cdr::BufferWriter) -> ::core::result::Result<(), zerodds_cdr::EncodeError> {\n");
    out.push_str("        match self {\n");
    for c in cases {
        let disc = c.value_labels.first().copied().unwrap_or(dd);
        out.push_str(&format!("            {name}::{}(__v) => {{\n", c.variant));
        out.push_str(&format!(
            "                <{switch_ty} as zerodds_cdr::CdrEncode>::encode(&(({disc}) as {switch_ty}), writer)?;\n"
        ));
        // Bounded-collection enforcement on the active arm (DDS-XTypes §7.4.3),
        // shared with the struct path. `__v` is the matched `&<arm-type>`.
        let mut checks = String::new();
        crate::struct_emit::emit_bound_checks_decl(&mut checks, &c.type_spec, &c.declarator, "__v");
        if !checks.is_empty() {
            out.push_str(&format!("                {checks}\n"));
        }
        out.push_str("                <_ as zerodds_cdr::CdrEncode>::encode(__v, writer)?;\n");
        out.push_str("            }\n");
    }
    out.push_str("        }\n");
    out.push_str("        ::core::result::Result::Ok(())\n");
    out.push_str("    }\n}\n");
}

fn emit_union_cdr_decode(out: &mut String, u: &UnionDef, cases: &[UnionCase], switch_ty: &str) {
    let name = escape_keyword(&u.name.text);
    out.push_str(&format!("\nimpl zerodds_cdr::CdrDecode for {name} {{\n"));
    out.push_str("    fn decode(reader: &mut zerodds_cdr::BufferReader<'_>) -> ::core::result::Result<Self, zerodds_cdr::DecodeError> {\n");
    out.push_str(&format!(
        "        let __disc = <{switch_ty} as zerodds_cdr::CdrDecode>::decode(reader)?;\n"
    ));
    out.push_str("        match __disc as i128 {\n");
    for c in cases {
        if c.value_labels.is_empty() {
            continue; // default-only case → falls into the _ arm
        }
        let pat = c
            .value_labels
            .iter()
            .map(::std::string::ToString::to_string)
            .collect::<Vec<_>>()
            .join(" | ");
        out.push_str(&format!(
            "            {pat} => ::core::result::Result::Ok({name}::{}(<{} as zerodds_cdr::CdrDecode>::decode(reader)?)),\n",
            c.variant, c.elem_type
        ));
    }
    if let Some(dc) = cases.iter().find(|c| c.is_default) {
        out.push_str(&format!(
            "            _ => ::core::result::Result::Ok({name}::{}(<{} as zerodds_cdr::CdrDecode>::decode(reader)?)),\n",
            dc.variant, dc.elem_type
        ));
    } else {
        out.push_str(&format!(
            "            _ => ::core::result::Result::Err(zerodds_cdr::DecodeError::InvalidEnum {{ kind: \"{}\", value: __disc as u32 }}),\n",
            u.name.text
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n}\n");
}

/// Evaluates a case-label ConstExpr to i128 (integer literal, optionally unary).
///
/// zerodds-lint: recursion-depth 64 (Const-Expr-Tree; bounded by IDL nesting)
fn const_label_as_i128(expr: &ConstExpr) -> Option<i128> {
    use zerodds_idl::ast::types::{ConstExpr as CE, LiteralKind, UnaryOp};
    match expr {
        CE::Literal(lit) if lit.kind == LiteralKind::Integer => parse_int_literal_i128(&lit.raw),
        CE::Unary { op, operand, .. } => {
            let v = const_label_as_i128(operand)?;
            match op {
                UnaryOp::Plus => Some(v),
                UnaryOp::Minus => Some(v.checked_neg()?),
                UnaryOp::BitNot => Some(!v),
            }
        }
        _ => None,
    }
}

fn parse_int_literal_i128(raw: &str) -> Option<i128> {
    let t = raw.trim_end_matches(['u', 'U', 'l', 'L']);
    if let Some(h) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
        i128::from_str_radix(h, 16).ok()
    } else if let Some(o) = t.strip_prefix("0o").or_else(|| t.strip_prefix("0O")) {
        i128::from_str_radix(o, 8).ok()
    } else if let Some(b) = t.strip_prefix("0b").or_else(|| t.strip_prefix("0B")) {
        i128::from_str_radix(b, 2).ok()
    } else {
        t.parse::<i128>().ok()
    }
}

fn emit_case_variant(out: &mut String, case: &Case) -> Result<()> {
    let variant_name = case.element.declarator.name();
    let elem_type = rust_type_for(&case.element.type_spec)?;
    out.push_str("    ");
    out.push_str(&capitalize(&variant_name.text));
    out.push('(');
    out.push_str(&elem_type);
    out.push_str("),\n");
    Ok(())
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().chain(c).collect(),
    }
}

#[allow(dead_code)]
fn switch_repr(spec: &SwitchTypeSpec) -> Result<&'static str> {
    use zerodds_idl::ast::types::IntegerType;
    match spec {
        SwitchTypeSpec::Integer(IntegerType::Int8) => Ok("i8"),
        SwitchTypeSpec::Integer(IntegerType::UInt8) => Ok("u8"),
        SwitchTypeSpec::Integer(IntegerType::Short | IntegerType::Int16) => Ok("i16"),
        SwitchTypeSpec::Integer(IntegerType::UShort | IntegerType::UInt16) => Ok("u16"),
        SwitchTypeSpec::Integer(IntegerType::Long | IntegerType::Int32) => Ok("i32"),
        SwitchTypeSpec::Integer(IntegerType::ULong | IntegerType::UInt32) => Ok("u32"),
        SwitchTypeSpec::Integer(IntegerType::LongLong | IntegerType::Int64) => Ok("i64"),
        SwitchTypeSpec::Integer(IntegerType::ULongLong | IntegerType::UInt64) => Ok("u64"),
        SwitchTypeSpec::Char | SwitchTypeSpec::Octet => Ok("u8"),
        SwitchTypeSpec::Boolean => Ok("u8"),
        SwitchTypeSpec::Scoped(_) => Err(RustGenError::Unsupported {
            what: "union discriminator scoped",
            at: 0,
        }),
    }
}
