// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Emits IDL `union` → Rust `enum` with a discriminator.
//!
//! XTypes 1.3 §7.4.1.4.5 union wire format:
//!
//! ```text
//! discriminator-value : <switch-type>
//! variant-body         : <case-type>
//! ```
//!
//! Rust mapping: tagged enum with a `repr` of the switch type. Variants
//! carry the respective case-body struct.

use zerodds_idl::ast::types::{Case, ConstExpr, Declarator, SwitchTypeSpec, TypeSpec, UnionDef};

use crate::error::{Result, RustGenError};
use crate::type_map::escape_keyword;
use crate::type_map::rust_type_for;

/// Emits a Rust enum representation of an IDL union.
pub fn emit_union(out: &mut String, u: &UnionDef) -> Result<()> {
    out.push_str("/// Generated by `zerodds-idl-rust` from IDL union.\n");
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub enum ");
    out.push_str(&escape_keyword(&u.name.text));
    out.push_str(" {\n");
    for case in &u.cases {
        emit_case_variant(out, case)?;
    }
    out.push_str("}\n\n");

    // Default impl: first variant
    if let Some(first) = u.cases.first() {
        let variant_name = &first.element.declarator.name().text;
        out.push_str("impl Default for ");
        out.push_str(&escape_keyword(&u.name.text));
        out.push_str(" {\n");
        out.push_str("    fn default() -> Self {\n");
        // Default value of the first variant
        let elem_type = rust_type_for(&first.element.type_spec)?;
        out.push_str(&format!(
            "        Self::{} (<{}>::default())\n",
            capitalize(variant_name),
            elem_type
        ));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    // CDR wire (classic + writer-agnostic): discriminator (switch-type)
    // followed by the active member. CORBA §15.3.2.6 / XTypes §7.4.1.4.5.
    // The CORBA codegen uses this with a classic (non-.xcdr2()) writer.
    let switch_ty = switch_repr(&u.switch_type)?;
    let cases = gather_union_cases(u)?;
    emit_union_cdr_encode(out, u, &cases, switch_ty);
    emit_union_cdr_decode(out, u, &cases, switch_ty);
    Ok(())
}

/// Pro Case aufbereitete Wire-Infos.
struct UnionCase {
    variant: String,
    elem_type: String,
    value_labels: Vec<i128>,
    is_default: bool,
    /// Declared type + declarator of the arm body — for bounded-collection
    /// enforcement (DDS-XTypes §7.4.3) on the active member at encode time.
    type_spec: TypeSpec,
    declarator: Declarator,
}

/// Evaluates the `case <expr>:` labels to i128 + collects variant/type per case.
fn gather_union_cases(u: &UnionDef) -> Result<Vec<UnionCase>> {
    use zerodds_idl::ast::types::CaseLabel;
    let mut out = Vec::with_capacity(u.cases.len());
    for case in &u.cases {
        let mut value_labels = Vec::new();
        let mut is_default = false;
        for label in &case.labels {
            match label {
                CaseLabel::Value(expr) => {
                    let v = const_label_as_i128(expr).ok_or(RustGenError::Unsupported {
                        what: "union case label (only integer-literal labels supported)",
                        at: 0,
                    })?;
                    value_labels.push(v);
                }
                CaseLabel::Default => is_default = true,
            }
        }
        out.push(UnionCase {
            variant: capitalize(&case.element.declarator.name().text),
            elem_type: rust_type_for(&case.element.type_spec)?,
            value_labels,
            is_default,
            type_spec: case.element.type_spec.clone(),
            declarator: case.element.declarator.clone(),
        });
    }
    Ok(out)
}

/// Discriminator value for the default arm: the smallest non-negative i128 that
/// matches no explicit label (roundtrip-stable, since both sides know the same
/// union definition).
fn default_discriminator(cases: &[UnionCase]) -> i128 {
    let used: std::collections::BTreeSet<i128> = cases
        .iter()
        .flat_map(|c| c.value_labels.iter().copied())
        .collect();
    let mut d = 0i128;
    while used.contains(&d) {
        d += 1;
    }
    d
}

fn emit_union_cdr_encode(out: &mut String, u: &UnionDef, cases: &[UnionCase], switch_ty: &str) {
    let name = escape_keyword(&u.name.text);
    let dd = default_discriminator(cases);
    // XTypes 1.3 §7.4.3.5.3: a FINAL union (FUNION, rule (26)) serializes as
    // disc + selected_member with NO frame. An APPENDABLE union (rule (30))
    // is self-delimited by a DHEADER on the XCDR2 path — required so a NESTED
    // or collection-element union of this type carries its own DHEADER on the
    // wire (the top-level frame only wraps the outermost type). Classic CDR
    // (CORBA/GIOP, max_align 8) has no DHEADER, so it stays plain. We detect
    // the path at runtime via `writer.max_alignment() == 4`.
    let appendable = matches!(
        crate::annotations::struct_extensibility(&u.annotations),
        crate::annotations::StructExtensibility::Appendable
    );
    out.push_str(&format!("\nimpl zerodds_cdr::CdrEncode for {name} {{\n"));
    out.push_str("    fn encode(&self, writer: &mut zerodds_cdr::BufferWriter) -> ::core::result::Result<(), zerodds_cdr::EncodeError> {\n");
    let (open, body_writer, indent) = if appendable {
        out.push_str("        if writer.max_alignment() == 4 {\n");
        out.push_str("            zerodds_cdr::struct_enc::encode_appendable(writer, |w| {\n");
        emit_union_match_encode(out, &name, cases, switch_ty, dd, "w", "                ");
        out.push_str("                Ok(())\n");
        out.push_str("            })?;\n");
        out.push_str("        } else {\n");
        (true, "writer", "            ")
    } else {
        (false, "writer", "        ")
    };
    emit_union_match_encode(out, &name, cases, switch_ty, dd, body_writer, indent);
    if open {
        out.push_str("        }\n");
    }
    out.push_str("        ::core::result::Result::Ok(())\n");
    out.push_str("    }\n}\n");
}

/// Emits the `match self { .. }` discriminator+member encode into `writer_expr`.
fn emit_union_match_encode(
    out: &mut String,
    name: &str,
    cases: &[UnionCase],
    switch_ty: &str,
    dd: i128,
    writer_expr: &str,
    indent: &str,
) {
    out.push_str(indent);
    out.push_str("match self {\n");
    for c in cases {
        let disc = c.value_labels.first().copied().unwrap_or(dd);
        out.push_str(&format!("{indent}    {name}::{}(__v) => {{\n", c.variant));
        out.push_str(&format!(
            "{indent}        <{switch_ty} as zerodds_cdr::CdrEncode>::encode(&(({disc}) as {switch_ty}), {writer_expr})?;\n"
        ));
        // Bounded-collection enforcement on the active arm (DDS-XTypes §7.4.3),
        // shared with the struct path. `__v` is the matched `&<arm-type>`.
        let mut checks = String::new();
        crate::struct_emit::emit_bound_checks_decl(&mut checks, &c.type_spec, &c.declarator, "__v");
        if !checks.is_empty() {
            out.push_str(&format!("{indent}        {checks}\n"));
        }
        out.push_str(&format!(
            "{indent}        <_ as zerodds_cdr::CdrEncode>::encode(__v, {writer_expr})?;\n"
        ));
        out.push_str(&format!("{indent}    }}\n"));
    }
    out.push_str(indent);
    out.push_str("}\n");
}

fn emit_union_cdr_decode(out: &mut String, u: &UnionDef, cases: &[UnionCase], switch_ty: &str) {
    let name = escape_keyword(&u.name.text);
    let appendable = matches!(
        crate::annotations::struct_extensibility(&u.annotations),
        crate::annotations::StructExtensibility::Appendable
    );
    out.push_str(&format!("\nimpl zerodds_cdr::CdrDecode for {name} {{\n"));
    out.push_str("    fn decode(reader: &mut zerodds_cdr::BufferReader<'_>) -> ::core::result::Result<Self, zerodds_cdr::DecodeError> {\n");
    if appendable {
        // XCDR2: strip the per-element DHEADER (rule (30)), symmetric to encode.
        out.push_str("        if reader.max_alignment() == 4 {\n");
        out.push_str(
            "            return zerodds_cdr::struct_enc::decode_appendable(reader, |r| {\n",
        );
        emit_union_disc_match_decode(
            out,
            &name,
            &u.name.text,
            cases,
            switch_ty,
            "r",
            "                ",
        );
        out.push_str("            });\n");
        out.push_str("        }\n");
    }
    emit_union_disc_match_decode(
        out,
        &name,
        &u.name.text,
        cases,
        switch_ty,
        "reader",
        "        ",
    );
    out.push_str("    }\n}\n");
}

/// Emits the `let __disc = ..; match __disc { .. }` decode into `reader_expr`.
fn emit_union_disc_match_decode(
    out: &mut String,
    name: &str,
    raw_name: &str,
    cases: &[UnionCase],
    switch_ty: &str,
    reader_expr: &str,
    indent: &str,
) {
    out.push_str(&format!(
        "{indent}let __disc = <{switch_ty} as zerodds_cdr::CdrDecode>::decode({reader_expr})?;\n"
    ));
    out.push_str(indent);
    out.push_str("match __disc as i128 {\n");
    for c in cases {
        if c.value_labels.is_empty() {
            continue; // default-only case → falls into the _ arm
        }
        let pat = c
            .value_labels
            .iter()
            .map(::std::string::ToString::to_string)
            .collect::<Vec<_>>()
            .join(" | ");
        out.push_str(&format!(
            "{indent}    {pat} => ::core::result::Result::Ok({name}::{}(<{} as zerodds_cdr::CdrDecode>::decode({reader_expr})?)),\n",
            c.variant, c.elem_type
        ));
    }
    if let Some(dc) = cases.iter().find(|c| c.is_default) {
        out.push_str(&format!(
            "{indent}    _ => ::core::result::Result::Ok({name}::{}(<{} as zerodds_cdr::CdrDecode>::decode({reader_expr})?)),\n",
            dc.variant, dc.elem_type
        ));
    } else {
        out.push_str(&format!(
            "{indent}    _ => ::core::result::Result::Err(zerodds_cdr::DecodeError::InvalidEnum {{ kind: \"{raw_name}\", value: __disc as u32 }}),\n"
        ));
    }
    out.push_str(indent);
    out.push_str("}\n");
}

/// Evaluates a case-label ConstExpr to i128 (integer literal, optionally unary).
///
/// zerodds-lint: recursion-depth 64 (Const-Expr-Tree; bounded by IDL nesting)
fn const_label_as_i128(expr: &ConstExpr) -> Option<i128> {
    // Resolves integer literals, enum literals (e.g. `case K_A:`), named consts,
    // and arithmetic — via the codegen const/enum registry (Bug H/L).
    crate::type_map::const_expr_as_i128(expr)
}

fn emit_case_variant(out: &mut String, case: &Case) -> Result<()> {
    let variant_name = case.element.declarator.name();
    let elem_type = rust_type_for(&case.element.type_spec)?;
    out.push_str("    ");
    out.push_str(&capitalize(&variant_name.text));
    out.push('(');
    out.push_str(&elem_type);
    out.push_str("),\n");
    Ok(())
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().chain(c).collect(),
    }
}

#[allow(dead_code)]
fn switch_repr(spec: &SwitchTypeSpec) -> Result<&'static str> {
    use zerodds_idl::ast::types::IntegerType;
    match spec {
        SwitchTypeSpec::Integer(IntegerType::Int8) => Ok("i8"),
        SwitchTypeSpec::Integer(IntegerType::UInt8) => Ok("u8"),
        SwitchTypeSpec::Integer(IntegerType::Short | IntegerType::Int16) => Ok("i16"),
        SwitchTypeSpec::Integer(IntegerType::UShort | IntegerType::UInt16) => Ok("u16"),
        SwitchTypeSpec::Integer(IntegerType::Long | IntegerType::Int32) => Ok("i32"),
        SwitchTypeSpec::Integer(IntegerType::ULong | IntegerType::UInt32) => Ok("u32"),
        SwitchTypeSpec::Integer(IntegerType::LongLong | IntegerType::Int64) => Ok("i64"),
        SwitchTypeSpec::Integer(IntegerType::ULongLong | IntegerType::UInt64) => Ok("u64"),
        SwitchTypeSpec::Char | SwitchTypeSpec::Octet => Ok("u8"),
        SwitchTypeSpec::Boolean => Ok("u8"),
        // An enum (or a typedef resolving to one) is the common scoped
        // discriminator. DDS enums are 32-bit on the wire (§7.4.5.1), so the
        // discriminant repr is i32 — matching `enum_emit`'s `#[repr(i32)]`.
        SwitchTypeSpec::Scoped(_) => Ok("i32"),
    }
}
