[package]
name = "zerodds-perf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Load generator, latency profiler, benchmark suite"
publish = false

[lints]
workspace = true

[[bin]]
name = "zerodds-perf"
path = "src/main.rs"

[dependencies]
zerodds-security-crypto = { version = "0.0.0", path = "../../crates/security-crypto" }
zerodds-monitor = { version = "0.0.0", path = "../../crates/monitor", default-features = false, features = ["std"] }
ring = "0.17"

[dev-dependencies]
