<?xml version="1.0" encoding="UTF-8"?>
<!--
    DDS-XML 1.0 §7.3.7 — Building Block Data Samples (chameleon).
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified"
           attributeFormDefault="unqualified">

    <xs:include schemaLocation="dds-xml_common.xsd"/>

    <!-- §7.3.7.1: Data-Sample-Format. <data> ist Top-Level. -->
    <xs:complexType name="dataSample">
        <xs:sequence>
            <!-- Spec §7.2.4.1: <element> tag for sequence/array.
                 §7.3.7.3.2: alternatively <item> tag allowed. -->
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>
