<?xml version="1.0" encoding="UTF-8"?>
<!--
    DDS-XML 1.0 §8.1 — DDS System Block Set (chameleon).
    Vereint QoS + Types + Domains + DomainParticipants + Applications.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified"
           attributeFormDefault="unqualified">

    <xs:include schemaLocation="dds-xml_qos_definitions_nonamespace.xsd"/>
    <xs:include schemaLocation="dds-xml_types_definitions_nonamespace.xsd"/>
    <xs:include schemaLocation="dds-xml_domains_definitions_nonamespace.xsd"/>
    <xs:include schemaLocation="dds-xml_domain_participants_definitions_nonamespace.xsd"/>
    <xs:include schemaLocation="dds-xml_applications_definitions_nonamespace.xsd"/>

    <!-- <dds>-Root: Top-Level fuer ein vollstaendiges System. -->
    <xs:complexType name="ddsSystem">
        <xs:sequence>
            <xs:element name="qos_library" type="qosLibrary"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="types" type="typeLibrary"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="domain_library" type="domainLibrary"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="domain_participant_library"
                        type="domainParticipantLibrary"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="application_library" type="applicationLibrary"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
