[package]
name = "zerodds-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "ZeroDDS Admin-CLI — Domain-Inspector, QoS-Validator, Discovery-Snapshot."
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-admin"
readme = "README.md"
keywords = ["dds", "admin", "cli", "operations", "tooling"]
categories = ["command-line-utilities", "development-tools"]
publish = true

[lints]
workspace = true

[[bin]]
name = "zerodds-admin"
path = "src/main.rs"

[dependencies]
zerodds-xml = { version = "1.0.0-rc.3.1", path = "../../crates/xml" }
zerodds-qos = { version = "1.0.0-rc.3.1", path = "../../crates/qos" }
zerodds-cli-common = { version = "1.0.0-rc.3.1", path = "../cli-common" }
zerodds-dcps = { version = "1.0.0-rc.3.1", path = "../../crates/dcps" }
zerodds-discovery = { version = "1.0.0-rc.3.1", path = "../../crates/discovery" }

[dev-dependencies]
