[package]
name = "zerodds-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "DDS-RPC 1.0 (formal/16-12-04): Requester/Replier-Runtime, Service-Mapping (IDL→Wire), Topic-Naming, function_call/dispatch_request, Evolution-Rules + Cross-PSM-Cross-Reference."
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-rpc"
readme = "README.md"
keywords = ["dds", "rpc", "request-reply", "middleware", "rmw"]
categories = ["network-programming", "asynchronous"]
publish = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
safety = []

[dependencies]
zerodds-dcps = { version = "1.0.0-rc.6", path = "../dcps" }
zerodds-idl = { version = "1.0.0-rc.6", path = "../idl" }
zerodds-qos = { version = "1.0.0-rc.6", path = "../qos" }
zerodds-rtps = { version = "1.0.0-rc.6", path = "../rtps" }
zerodds-types = { version = "1.0.0-rc.6", path = "../types" }
zerodds-xml = { version = "1.0.0-rc.6", path = "../xml" }

[dev-dependencies]
