// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! IDL `valuetype` → Rust trait + Marshalling.
//!
//! Mapping (CORBA 3.3 §7.4.5.4):
//! - `valuetype V { ... };` → `pub trait V: ValueBase + ...` plus
//!   ValueBase-Marshalling.
//! - State-Member (`public T x;`/`private T x;`) → trait-method
//!   für read-Zugriff (Public-State); Encode/Decode kopiert State.
//! - `init`-Konstruktoren → freie Funktion `<v>_init_<name>(...)`.
//! - Inheritance — werden in `bases` über trait-Bound abgebildet.
//!
//! **Phase-1-Scope**: nur die Trait-Definition + Public-State. Volle
//! ValueBase-Wire-Marshalling-Logic ist Phase-2.

use zerodds_idl::ast::types::{
    Declarator, Export, InitDcl, StateVisibility, ValueDef, ValueElement,
};

use crate::error::Result;

/// Emittiert eine IDL-Valuetype-Definition als Rust-Trait + Skeleton.
pub fn emit_valuetype(out: &mut String, v: &ValueDef) -> Result<()> {
    let name = &v.name.text;
    out.push_str("/// Generated by `zerodds-corba-rust` from IDL valuetype.\n");

    // §4.2 Inheritance: trait-bounds aus inheritance.bases.
    let mut bounds =
        String::from("zerodds_corba_rust::ValueBase + ::core::marker::Send + ::core::marker::Sync");
    if let Some(inh) = &v.inheritance {
        for base in &inh.bases {
            let path = base
                .parts
                .iter()
                .map(|p| p.text.as_str())
                .collect::<Vec<_>>()
                .join("::");
            bounds.push_str(&format!(" + {path}"));
        }
    }

    // §6.1 Repository-ID als freier pub-const (dyn-Compatibility) —
    // via `zerodds-corba-codegen::build_repository_id` (CORBA 3.3
    // §10.7.3.1 Format).
    let repo_id = zerodds_corba_codegen::build_repository_id(&[], name, 1, 0);
    let repo_const = name.to_ascii_uppercase();
    out.push_str(&format!(
        "/// CORBA Repository-ID fuer Valuetype `{name}` (Spec §10.7.3.1).\npub const {repo_const}_REPOSITORY_ID: &str = \"{repo_id}\";\n"
    ));
    out.push_str(&format!("pub trait {name}: {bounds} {{\n"));

    for element in &v.elements {
        emit_value_element(out, element)?;
    }

    out.push_str("}\n\n");

    // §4.3 Init-Konstruktoren als freie Funktionen.
    for element in &v.elements {
        if let ValueElement::Init(init) = element {
            emit_init_function(out, name, init)?;
        }
    }

    Ok(())
}

fn emit_init_function(out: &mut String, value_name: &str, init: &InitDcl) -> Result<()> {
    let init_name = &init.name.text;
    let fn_name = format!("{}_init_{}", value_name.to_lowercase(), init_name);
    let mut params = String::new();
    for (idx, p) in init.params.iter().enumerate() {
        if idx > 0 {
            params.push_str(", ");
        }
        let ty = zerodds_idl_rust::type_map::rust_type_for(&p.type_spec)?;
        params.push_str(&format!("{}: {ty}", p.name.text));
    }
    out.push_str(&format!(
        "/// IDL `factory {init_name}` Konstruktor fuer Valuetype `{value_name}`.\n"
    ));
    out.push_str("/// Phase-2 wired das an die ValueFactory-Registry; Phase-1 ist Platzhalter.\n");
    out.push_str(&format!(
        "pub fn {fn_name}({params}) -> ::core::result::Result<::std::boxed::Box<dyn {value_name}>, zerodds_corba_rust::CorbaException> {{\n"
    ));
    // Use of params (silence unused warnings)
    for p in &init.params {
        out.push_str(&format!("    let _ = {};\n", p.name.text));
    }
    out.push_str(
        "    ::core::result::Result::Err(zerodds_corba_rust::CorbaException::SystemException {\n",
    );
    out.push_str("        minor: 0,\n");
    out.push_str("        message: \"corba-rust: ValueFactory init not yet wired (Phase-2)\",\n");
    out.push_str("    })\n");
    out.push_str("}\n\n");
    Ok(())
}

fn emit_value_element(out: &mut String, element: &ValueElement) -> Result<()> {
    match element {
        ValueElement::State(sm) => {
            let ty = zerodds_idl_rust::type_map::rust_type_for(&sm.type_spec)?;
            let public = matches!(sm.visibility, StateVisibility::Public);
            for declarator in &sm.declarators {
                let name = match declarator {
                    Declarator::Simple(n) => &n.text,
                    Declarator::Array(a) => &a.name.text,
                };
                let prefix = if public { "" } else { "_priv_" };
                out.push_str(&format!(
                    "    /// State-member `{name}` (public={public}).\n"
                ));
                out.push_str(&format!("    fn {prefix}{name}(&self) -> {ty};\n"));
            }
        }
        ValueElement::Init(_) => {
            // Init-Konstruktoren werden als freie Funktionen
            // `<valuetype>_init_<name>(...)` emittiert (Phase-2).
        }
        ValueElement::Export(Export::Op(op)) => {
            crate::interface_emit::emit_op_trait_method_pub(out, op)?;
        }
        ValueElement::Export(Export::Attr(attr)) => {
            crate::interface_emit::emit_attr_trait_method_pub(out, attr)?;
        }
        ValueElement::Export(_) => {
            // Type/Const/Except-Exports werden im idl-rust-DataType-
            // Pfad emittiert.
        }
    }
    Ok(())
}
