// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors

//! Adversarial IDL → Elixir corpus, gated on the real `elixirc` toolchain.
//!
//! Every case is generated by the backend and then *compiled* by `elixirc`, so
//! a construct that emits syntactically or semantically invalid Elixir fails
//! here rather than silently shipping. Three axes:
//!
//! * `reserved_keyword_corpus` — each Elixir reserved word placed at every IDL
//!   position where it can be an identifier (member, struct, enum + enumerator,
//!   module, const, union branch), then compiled.
//! * `construct_corpus` — each IDL construct minimally (fixed, enum `@value`,
//!   const of every scalar type, struct inheritance, unions over every
//!   discriminator kind, bitset, bitmask, `@optional`/`@extensibility`,
//!   sequence, multidimensional array, map, nested + reopened module).
//! * `compose_multifile` — two IDLs generated separately under distinct package
//!   namespaces and merged into one Elixir source, compiled together.
//!
//! Skips (loudly) when `elixirc` is not on PATH — the toolchain-free structural
//! checks in `invariants.rs` still run everywhere.

#![allow(
    clippy::expect_used,
    clippy::panic,
    clippy::print_stderr,
    clippy::unwrap_used
)]

use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

use zerodds_idl::config::ParserConfig;
use zerodds_idl_elixir::{ElixirGenOptions, generate_elixir_module};

const RESERVED: &[&str] = &[
    "true", "false", "nil", "when", "and", "or", "not", "in", "fn", "do", "end", "catch", "rescue",
    "after", "else",
];

fn elixirc_available() -> bool {
    Command::new("elixirc")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Generates Elixir from `src` under package `pkg`, or `None` if the IDL itself
/// rejects the source (so callers can skip IDL-illegal identifiers).
fn gen_src(src: &str, pkg: &str) -> Option<String> {
    let ast = zerodds_idl::parse(src, &ParserConfig::default()).ok()?;
    let opts = ElixirGenOptions {
        module_name: pkg.to_string(),
    };
    generate_elixir_module(&ast, &opts).ok()
}

static SEQ: AtomicUsize = AtomicUsize::new(0);

/// Compiles Elixir source with `elixirc`, returning `Err(stderr)` on failure.
fn elixir_compiles(source: &str) -> Result<(), String> {
    let n = SEQ.fetch_add(1, Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!("idlelixir_corpus_{}_{n}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("mkdir");
    let file = dir.join("gen_src.ex");
    std::fs::write(&file, source).expect("write");
    let out = Command::new("elixirc")
        .arg("--ignore-module-conflict")
        .arg("-o")
        .arg(&dir)
        .arg(&file)
        .current_dir(&dir)
        .output()
        .expect("spawn elixirc");
    let res = if out.status.success() {
        Ok(())
    } else {
        Err(String::from_utf8_lossy(&out.stderr).to_string())
    };
    let _ = std::fs::remove_dir_all(&dir);
    res
}

fn assert_compiles(label: &str, src: &str, pkg: &str) {
    let Some(code) = gen_src(src, pkg) else {
        eprintln!("SKIP {label}: IDL rejects `{src}`");
        return;
    };
    if let Err(e) = elixir_compiles(&code) {
        panic!(
            "{label}: generated Elixir failed to compile:\n{e}\n--- IDL ---\n{src}\n--- gen_src ---\n{code}"
        );
    }
}

#[test]
fn reserved_keyword_corpus() {
    if !elixirc_available() {
        eprintln!("SKIP reserved_keyword_corpus: `elixirc` not on PATH");
        return;
    }
    for (i, &w) in RESERVED.iter().enumerate() {
        let pkg = format!("RwGen{i}");
        // Each position where the word can be an IDL identifier.
        let positions = [
            ("member", format!("@final struct S {{ long {w}; }};")),
            ("struct-name", format!("@final struct {w} {{ long v; }};")),
            (
                "enum+enumerator",
                format!("enum {w} {{ {w}_a, {w}_b, {w}_c }};"),
            ),
            (
                "module",
                format!("module {w} {{ @final struct S {{ long v; }}; }};"),
            ),
            ("const", format!("const long {w} = 1;")),
            (
                "union-branch",
                format!("union U switch (long) {{ case 1: long {w}; default: long {w}_d; }};"),
            ),
        ];
        for (pos, src) in positions {
            assert_compiles(&format!("reserved `{w}` @ {pos}"), &src, &pkg);
        }
    }
}

#[test]
fn construct_corpus() {
    if !elixirc_available() {
        eprintln!("SKIP construct_corpus: `elixirc` not on PATH");
        return;
    }
    let cases: &[(&str, &str)] = &[
        (
            "primitives",
            "@final struct P { boolean b; octet o; char c; wchar w; short sh; unsigned short ush; long l; unsigned long ul; long long ll; unsigned long long ull; int8 i8; uint8 u8; int16 i16; uint16 u16; int32 i32; uint32 u32; int64 i64; uint64 u64; float f; double d; long double ld; };",
        ),
        (
            "strings",
            "@final struct St { string s; wstring w; string<8> bs; wstring<8> bw; };",
        ),
        ("fixed", "@final struct Fx { fixed<10,2> amount; };"),
        (
            "enum-value",
            "enum E { @value(5) A, @value(10) B, C }; @final struct S { E e; };",
        ),
        (
            "const-all-types",
            "const long CI = -1; const unsigned long CU = 0xFF; const boolean CB = TRUE; const float CF = 1.5; const double CD = 2.5; const char CC = 'x'; const string CS = \"s\"; const octet CO = 7;",
        ),
        (
            "struct-inheritance",
            "@final struct Base { long a; long b; }; @final struct Mid : Base { long c; }; @final struct Leaf : Mid { long d; };",
        ),
        (
            "union-integer-disc",
            "union U switch (long) { case 1: long a; case 2: double b; default: octet c; };",
        ),
        (
            "union-enum-disc",
            "enum Col { R, G, B }; union U switch (Col) { case R: long a; case G: double b; default: octet c; };",
        ),
        (
            "union-char-disc",
            "union U switch (char) { case 'A': long a; case 'B': double b; };",
        ),
        (
            "union-bool-disc",
            "union U switch (boolean) { case TRUE: long t; case FALSE: double f; };",
        ),
        (
            "union-mutable",
            "@mutable union U switch (long) { case 1: long a; case 2: double b; };",
        ),
        (
            "bitset",
            "bitset Bits { bitfield<3> lo; bitfield<5> hi; bitfield<1> flag; };",
        ),
        ("bitmask", "bitmask Flags { fa, fb, fc, fd };"),
        ("bitmask-bit-bound", "@bit_bound(16) bitmask F16 { a, b };"),
        (
            "optional",
            "@appendable struct O { long id; @optional long note; };",
        ),
        (
            "must-understand",
            "@mutable struct M { @must_understand long id; long v; };",
        ),
        ("extensibility-final", "@final struct F { long a; };"),
        (
            "extensibility-appendable",
            "@appendable struct A { long a; };",
        ),
        (
            "extensibility-mutable",
            "@mutable struct Mu { long a; long b; };",
        ),
        (
            "sequence",
            "@final struct Sq { sequence<long> xs; sequence<double, 4> ys; sequence<octet> raw; };",
        ),
        (
            "sequence-of-struct",
            "@final struct El { long v; }; @final struct Sq { sequence<El> es; };",
        ),
        (
            "array-multidim",
            "@final struct Ar { long grid[2][3]; long cube[2][2][2]; };",
        ),
        (
            "map",
            "@final struct Mp { map<long, string> m; map<long, double, 8> bm; };",
        ),
        (
            "module-nested",
            "module a { module b { module c { @final struct Deep { long v; }; }; }; };",
        ),
        (
            "module-reopened",
            "module M { @final struct A { long x; }; }; module M { @final struct B { long y; }; };",
        ),
        (
            "cross-module-ref",
            "module a { @final struct R { long v; }; }; module b { @final struct S { a::R r; }; };",
        ),
        (
            "interface-nested-types",
            "interface Svc { struct Req { long id; }; struct Resp { long code; }; };",
        ),
        (
            "typedef",
            "typedef sequence<long> LSeq; typedef long Score; @final struct T { LSeq xs; Score s; };",
        ),
        ("key", "@final struct K { @key long id; long payload; };"),
        (
            "nested-struct",
            "@final struct Inner { long v; }; @final struct Outer { Inner i; long tag; };",
        ),
    ];
    for (label, src) in cases {
        assert_compiles(label, src, "CtorGen");
    }
}

#[test]
fn compose_multifile() {
    if !elixirc_available() {
        eprintln!("SKIP compose_multifile: `elixirc` not on PATH");
        return;
    }
    // Two IDLs generated SEPARATELY under distinct package namespaces, then
    // merged into one Elixir source (each carries its own `Wire` module, so
    // there is no collision) and compiled together — the idiomatic Elixir way to
    // combine independently generated files in one project.
    let a = gen_src(
        "enum Mode { IDLE, RUN }; @final struct Alpha { long id; Mode m; sequence<long> xs; };",
        "AlphaGen",
    )
    .expect("gen_src A");
    let b = gen_src(
        "@mutable struct Beta { @must_understand long id; @optional string note; }; \
         union BetaU switch (long) { case 1: long a; default: double b; };",
        "BetaGen",
    )
    .expect("gen_src B");

    let merged = format!("{a}\n{b}\n");
    if let Err(e) = elixir_compiles(&merged) {
        panic!(
            "compose_multifile: merged Elixir failed to compile:\n{e}\n--- merged ---\n{merged}"
        );
    }
}
