// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors
//! Projekt-Scaffolding — die „extra Meile".
//!
//! RTI (`-example`) und Fast DDS (`-example`) erzeugen optional ein
//! Build-Projekt; Cyclone gar nicht. `zerodds-idlc` bietet mit
//! `--scaffold` pro Backend die idiomatische Build-Datei an, sodass die
//! generierten Stubs ohne Handarbeit kompilierbar sind:
//!
//! * Rust   → `Cargo.toml`
//! * C/C++  → `CMakeLists.txt`
//! * C#     → `<base>.csproj`
//! * Java   → `pom.xml`
//! * Python → `pyproject.toml`
//! * TS     → `package.json` + `tsconfig.json`
//!
//! Opt-in: ohne `--scaffold` wird nichts davon geschrieben. Bestehende
//! Build-Dateien werden nicht ueberschrieben (der Aufrufer prueft das).

use crate::Backend;

/// Version der zerodds-Runtime-Pakete, auf die ein frisch erzeugtes Scaffold
/// zeigt. An die `zerodds-idlc`-Version gekoppelt (beide erben
/// `version.workspace`), damit Codegen und Runtime nie auseinanderlaufen und
/// kein Versions-Marker im Datei-Body von Hand gepflegt werden muss.
const RUNTIME_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Liefert die Scaffolding-Build-Dateien fuer ein Backend als
/// `(Dateiname, Inhalt)`-Paare. `base` ist der IDL-Basisname.
///
/// Die Manifeste deklarieren die Runtime-Abhaengigkeiten, die der generierte
/// Code tatsaechlich braucht (Rust: `zerodds-cdr`+`zerodds-dcps`+
/// `zerodds-types`; C/C++: `find_package(zerodds)` + Link auf
/// `zerodds::zerodds-c`/`-cpp`; TS: `@zerodds/cdr`+`@zerodds/types`), sodass
/// ein Scaffold ohne Handarbeit baut. Ziele, deren Runtime nur ueber eine
/// Registry (npm/Maven/NuGet/PyPI) oder einen installierten SDK-Baum erreichbar
/// ist, dokumentieren das im Kopfkommentar der jeweiligen Datei.
#[must_use]
pub fn scaffold_files(backend: Backend, base: &str) -> Vec<(String, String)> {
    match backend {
        Backend::Rust => vec![("Cargo.toml".to_string(), rust_cargo_toml(base))],
        Backend::C => vec![("CMakeLists.txt".to_string(), cmake(base, "C", "zerodds-c"))],
        Backend::Cpp => vec![(
            "CMakeLists.txt".to_string(),
            cmake(base, "CXX", "zerodds-cpp"),
        )],
        Backend::CSharp => vec![(format!("{base}.csproj"), csproj())],
        Backend::Java => vec![("pom.xml".to_string(), pom_xml(base))],
        Backend::Python => vec![("pyproject.toml".to_string(), pyproject(base))],
        Backend::Ts => vec![
            ("package.json".to_string(), package_json(base)),
            ("tsconfig.json".to_string(), tsconfig()),
        ],
        Backend::Go => vec![("go.mod".to_string(), format!("module {base}\n\ngo 1.21\n"))],
        Backend::Ada => vec![(
            format!("{base}.gpr"),
            format!("project {base} is\nend {base};\n"),
        )],
        Backend::Zig => vec![(
            "build.zig".to_string(),
            format!("// zig build script for {base}\n"),
        )],
        Backend::Nim => vec![(
            format!("{base}.nimble"),
            format!("# nimble file for {base}\n"),
        )],
        Backend::D => vec![(
            "dub.json".to_string(),
            format!("{{ \"name\": \"{}\" }}\n", base.to_lowercase()),
        )],
        Backend::Elixir => vec![("mix.exs".to_string(), format!("# mix project for {base}\n"))],
        Backend::OCaml => vec![(
            "dune-project".to_string(),
            format!("(lang dune 3.0)\n; project {base}\n"),
        )],
        Backend::Julia => vec![("Project.toml".to_string(), format!("name = \"{base}\"\n"))],
        Backend::Lua => vec![(
            format!("{}-dev-1.rockspec", base.to_lowercase()),
            format!("package = \"{}\"\n", base.to_lowercase()),
        )],
        Backend::Swift => vec![(
            "Package.swift".to_string(),
            format!("// swift-tools-version:5.9\n// package {base}\n"),
        )],
    }
}

fn rust_cargo_toml(base: &str) -> String {
    let ver = RUNTIME_VERSION;
    // Der generierte `<base>.rs` implementiert `zerodds_dcps::DdsType`
    // (encode/decode/TYPE_IDENTIFIER); die Bodies rufen `zerodds_cdr` (Wire-
    // Codec) und `zerodds_types` (TypeIdentifier). Alle drei Runtime-Crates
    // muessen daher deklariert sein — mit nur `zerodds-cdr` bricht der Build.
    // `--corba`/RPC-Interface-Stubs brauchen zusaetzlich `zerodds-rpc`.
    format!(
        "# Generated by zerodds-idlc --scaffold.\n\
         #\n\
         # Baubares Minimalprojekt. Gegen die veroeffentlichten Crates:\n\
         #     cargo build\n\
         # Gegen einen lokalen Checkout stattdessen unten anfuegen:\n\
         #     [patch.crates-io]\n\
         #     zerodds-cdr   = {{ path = \"/pfad/zu/zero-dds/crates/cdr\" }}\n\
         #     zerodds-dcps  = {{ path = \"/pfad/zu/zero-dds/crates/dcps\" }}\n\
         #     zerodds-types = {{ path = \"/pfad/zu/zero-dds/crates/types\" }}\n\
         [package]\n\
         name = \"{base}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\n\
         [lib]\n\
         path = \"{base}.rs\"\n\n\
         [dependencies]\n\
         # Wire-Codec: BufferWriter/Reader, CdrEncode/CdrDecode.\n\
         zerodds-cdr = \"{ver}\"\n\
         # DCPS-Runtime: der DdsType-Trait, den der generierte Code impl'iert.\n\
         zerodds-dcps = \"{ver}\"\n\
         # XTypes: TypeIdentifier fuer die TYPE_IDENTIFIER-Konstante.\n\
         zerodds-types = \"{ver}\"\n"
    )
}

fn cmake(base: &str, lang: &str, runtime_target: &str) -> String {
    // Beide Backends emittieren einen Header (C: <base>.h, C++:
    // <base>.hpp) — eine INTERFACE-Library reicht. Der Header inkludiert die
    // zerodds-Runtime-Header (dds/…, zerodds/…), deshalb `find_package` +
    // Link auf das exportierte Runtime-Target `zerodds::zerodds-c`/`-cpp`
    // (identisch zum SDK-Consumer-Muster in cmake/tests/sdk-consumer).
    format!(
        "# Generated by zerodds-idlc --scaffold.\n\
         #\n\
         # Baubar gegen einen installierten zerodds-SDK (find_package unten\n\
         # loest zeroddsConfig.cmake aus einem `cmake --install`-Stagingbaum\n\
         # auf CMAKE_PREFIX_PATH auf):\n\
         #     cmake -S . -B build -DCMAKE_PREFIX_PATH=/pfad/zu/zerodds-install\n\
         #     cmake --build build\n\
         cmake_minimum_required(VERSION 3.16)\n\
         project({base} {lang})\n\n\
         find_package(zerodds CONFIG REQUIRED)\n\n\
         add_library({base} INTERFACE)\n\
         target_include_directories({base} INTERFACE ${{CMAKE_CURRENT_SOURCE_DIR}})\n\
         target_link_libraries({base} INTERFACE zerodds::{runtime_target})\n"
    )
}

fn csproj() -> String {
    let ver = RUNTIME_VERSION;
    // Der generierte Code nutzt `using Omg.Types;` und Typen aus dem
    // `ZeroDDS.Cdr`-Namespace → PackageReference auf das ZeroDDS.Cdr-NuGet.
    // Braucht die Registry (bzw. eine lokale `nuget.config`-Quelle); ohne
    // erreichbares ZeroDDS.Cdr-Paket ist das Projekt ein Geruest.
    format!(
        "<!-- Generated by zerodds-idlc --scaffold. -->\n\
         <!-- Runtime: ZeroDDS.Cdr von NuGet (oder lokaler nuget.config-Quelle). -->\n\
         <Project Sdk=\"Microsoft.NET.Sdk\">\n\
         \x20 <PropertyGroup>\n\
         \x20   <TargetFramework>net8.0</TargetFramework>\n\
         \x20   <Nullable>enable</Nullable>\n\
         \x20   <LangVersion>latest</LangVersion>\n\
         \x20 </PropertyGroup>\n\
         \x20 <ItemGroup>\n\
         \x20   <PackageReference Include=\"ZeroDDS.Cdr\" Version=\"{ver}\" />\n\
         \x20 </ItemGroup>\n\
         </Project>\n"
    )
}

fn pom_xml(base: &str) -> String {
    let ver = RUNTIME_VERSION;
    format!(
        "<!-- Generated by zerodds-idlc --scaffold. -->\n\
         <project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n\
         \x20        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n\
         \x20        xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 \
         http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n\
         \x20 <modelVersion>4.0.0</modelVersion>\n\
         \x20 <groupId>org.zerodds.generated</groupId>\n\
         \x20 <artifactId>{base}</artifactId>\n\
         \x20 <version>0.1.0</version>\n\
         \x20 <properties>\n\
         \x20   <maven.compiler.release>17</maven.compiler.release>\n\
         \x20   <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n\
         \x20 </properties>\n\
         \x20 <!-- Runtime: org.zerodds:omgdds aus Maven Central (oder lokalem\n\
         \x20      Repository). Ohne erreichbares Artefakt ist dies ein Geruest. -->\n\
         \x20 <dependencies>\n\
         \x20   <dependency>\n\
         \x20     <groupId>org.zerodds</groupId>\n\
         \x20     <artifactId>omgdds</artifactId>\n\
         \x20     <version>{ver}</version>\n\
         \x20   </dependency>\n\
         \x20 </dependencies>\n\
         </project>\n"
    )
}

fn pyproject(base: &str) -> String {
    // Der generierte Code importiert `from zerodds.idl import …`; die
    // Runtime ist das `zerodds`-PyPI-Paket (maturin-Extension). Braucht die
    // Registry (oder ein lokal installiertes Wheel).
    let ver = RUNTIME_VERSION;
    format!(
        "# Generated by zerodds-idlc --scaffold.\n\
         # Runtime: das `zerodds`-Paket von PyPI (oder ein lokal installiertes\n\
         # Wheel). Ohne erreichbares Paket ist dies ein Geruest.\n\
         [build-system]\n\
         requires = [\"setuptools>=64\"]\n\
         build-backend = \"setuptools.build_meta\"\n\n\
         [project]\n\
         name = \"{base}\"\n\
         version = \"0.1.0\"\n\
         requires-python = \">=3.10\"\n\
         dependencies = [\"zerodds>={ver}\"]\n"
    )
}

fn package_json(base: &str) -> String {
    // Der generierte TS-Code importiert aus `@zerodds/cdr` (Wire-Codec) und
    // `@zerodds/types` (Typsystem) — beide muessen deklariert sein. Braucht
    // die npm-Registry (oder lokale `node_modules`/`file:`-Quelle).
    let ver = RUNTIME_VERSION;
    format!(
        "{{\n\
         \x20 \"name\": \"{base}\",\n\
         \x20 \"version\": \"0.1.0\",\n\
         \x20 \"type\": \"module\",\n\
         \x20 \"main\": \"{base}.ts\",\n\
         \x20 \"comment\": \"Runtime @zerodds/cdr + @zerodds/types von npm (oder file:-Quelle).\",\n\
         \x20 \"dependencies\": {{\n\
         \x20   \"@zerodds/cdr\": \"^{ver}\",\n\
         \x20   \"@zerodds/types\": \"^{ver}\"\n\
         \x20 }},\n\
         \x20 \"devDependencies\": {{\n\
         \x20   \"typescript\": \"^5.4.0\"\n\
         \x20 }}\n\
         }}\n"
    )
}

fn tsconfig() -> String {
    "{\n\
     \x20 \"compilerOptions\": {\n\
     \x20   \"target\": \"ES2022\",\n\
     \x20   \"module\": \"ES2022\",\n\
     \x20   \"moduleResolution\": \"bundler\",\n\
     \x20   \"strict\": true,\n\
     \x20   \"declaration\": true\n\
     \x20 }\n\
     }\n"
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_scaffold_is_cargo_toml() {
        let files = scaffold_files(Backend::Rust, "robot");
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].0, "Cargo.toml");
        assert!(files[0].1.contains("name = \"robot\""));
        assert!(files[0].1.contains("path = \"robot.rs\""));
        assert!(files[0].1.contains("zerodds-cdr"));
    }

    #[test]
    fn rust_scaffold_declares_all_runtime_crates() {
        // Der generierte Code impl'iert `zerodds_dcps::DdsType`, dessen Bodies
        // `zerodds_cdr` + `zerodds_types` rufen — nur `zerodds-cdr` reicht nicht.
        let toml = &scaffold_files(Backend::Rust, "robot")[0].1;
        let ver = RUNTIME_VERSION;
        assert!(toml.contains(&format!("zerodds-cdr = \"{ver}\"")));
        assert!(toml.contains(&format!("zerodds-dcps = \"{ver}\"")));
        assert!(toml.contains(&format!("zerodds-types = \"{ver}\"")));
    }

    #[test]
    fn ts_scaffold_has_two_files() {
        let files = scaffold_files(Backend::Ts, "chat");
        assert_eq!(files.len(), 2);
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&"package.json"));
        assert!(names.contains(&"tsconfig.json"));
    }

    #[test]
    fn ts_scaffold_declares_cdr_and_types() {
        // Der generierte TS-Code importiert aus @zerodds/cdr UND @zerodds/types.
        let pkg = &scaffold_files(Backend::Ts, "chat")[0].1;
        assert_eq!(scaffold_files(Backend::Ts, "chat")[0].0, "package.json");
        assert!(pkg.contains("@zerodds/cdr"));
        assert!(pkg.contains("@zerodds/types"));
    }

    #[test]
    fn cpp_and_c_use_cmake() {
        assert_eq!(scaffold_files(Backend::C, "x")[0].0, "CMakeLists.txt");
        assert_eq!(scaffold_files(Backend::Cpp, "x")[0].0, "CMakeLists.txt");
        assert!(
            scaffold_files(Backend::Cpp, "x")[0]
                .1
                .contains("project(x CXX)")
        );
        assert!(
            scaffold_files(Backend::C, "x")[0]
                .1
                .contains("project(x C)")
        );
    }

    #[test]
    fn cmake_scaffold_finds_and_links_zerodds() {
        // Ohne find_package/Link kompiliert der Header nie gegen die Runtime.
        let c = &scaffold_files(Backend::C, "x")[0].1;
        assert!(c.contains("find_package(zerodds CONFIG REQUIRED)"));
        assert!(c.contains("target_link_libraries(x INTERFACE zerodds::zerodds-c)"));
        let cpp = &scaffold_files(Backend::Cpp, "x")[0].1;
        assert!(cpp.contains("find_package(zerodds CONFIG REQUIRED)"));
        assert!(cpp.contains("target_link_libraries(x INTERFACE zerodds::zerodds-cpp)"));
    }

    #[test]
    fn csharp_scaffold_named_after_base() {
        let files = scaffold_files(Backend::CSharp, "robot");
        assert_eq!(files[0].0, "robot.csproj");
        assert!(files[0].1.contains("Microsoft.NET.Sdk"));
    }

    #[test]
    fn csharp_scaffold_references_runtime() {
        // Der generierte Code nutzt `using Omg.Types;` + ZeroDDS.Cdr-Typen.
        let csproj = &scaffold_files(Backend::CSharp, "robot")[0].1;
        assert!(csproj.contains("<PackageReference Include=\"ZeroDDS.Cdr\""));
    }

    #[test]
    fn java_scaffold_is_pom() {
        let files = scaffold_files(Backend::Java, "robot");
        assert_eq!(files[0].0, "pom.xml");
        assert!(files[0].1.contains("<artifactId>robot</artifactId>"));
    }

    #[test]
    fn java_scaffold_depends_on_omgdds() {
        let pom = &scaffold_files(Backend::Java, "robot")[0].1;
        assert!(pom.contains("<groupId>org.zerodds</groupId>"));
        assert!(pom.contains("<artifactId>omgdds</artifactId>"));
    }

    #[test]
    fn python_scaffold_is_pyproject() {
        let files = scaffold_files(Backend::Python, "robot");
        assert_eq!(files[0].0, "pyproject.toml");
        assert!(files[0].1.contains("name = \"robot\""));
    }

    #[test]
    fn python_scaffold_depends_on_zerodds() {
        // Der generierte Code importiert `from zerodds.idl import …`.
        let py = &scaffold_files(Backend::Python, "robot")[0].1;
        assert!(py.contains("dependencies = [\"zerodds>="));
    }
}
