[package]
name = "zerodds-xrce-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "XRCE agent running in Full/Standard profile"
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-xrce-agent"
readme = "README.md"
keywords = ["dds", "xrce", "agent"]
categories = ["embedded", "network-programming"]
publish = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
safety = []

[dependencies]
zerodds-xrce = { version = "1.0.0-rc.3.1", path = "../xrce" }

[dev-dependencies]
