/* SPDX-License-Identifier: Apache-2.0
 * rmw_zerodds — ROS 2 RMW implementation backed by ZeroDDS.
 * Generated by cbindgen — do not edit. */

#ifndef RMW_ZERODDS_H_
#define RMW_ZERODDS_H_

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Opaque-Handle: rmw_zerodds Client (request-Pub + reply-Sub auf
 * `<service>_Request` / `<service>_Reply`).
 */
typedef struct rmw_zerodds_RmwZerodsClient rmw_zerodds_RmwZerodsClient;

/**
 * Opaque-Handle: rmw_zerodds Context (1:1 zu einem Domain-Participant-
 * Init). Hardcoded Domain 0 in aktuelle Distros; spaeter aus init_options.
 */
typedef struct rmw_zerodds_RmwZerodsContext rmw_zerodds_RmwZerodsContext;

/**
 * Opaque Node-Handle.
 */
typedef struct rmw_zerodds_RmwZerodsNode rmw_zerodds_RmwZerodsNode;

/**
 * Opaque Publisher-Handle. Wrapt einen ZeroDDS-Writer.
 */
typedef struct rmw_zerodds_RmwZerodsPublisher rmw_zerodds_RmwZerodsPublisher;

/**
 * Opaque-Handle: rmw_zerodds Service (request-Sub + reply-Pub).
 */
typedef struct rmw_zerodds_RmwZerodsService rmw_zerodds_RmwZerodsService;

/**
 * Opaque Subscription-Handle. Wrapt einen ZeroDDS-Reader.
 */
typedef struct rmw_zerodds_RmwZerodsSubscription rmw_zerodds_RmwZerodsSubscription;

/**
 * Wait-Set-Handle. Phase-B implementiert: Poll-basiert, nicht
 * edge-triggered. Caller fuegt Subscriptions hinzu, ruft `wait`
 * und bekommt zurueck welche Indices Daten bereit haben.
 */
typedef struct rmw_zerodds_RmwZerodsWaitSet rmw_zerodds_RmwZerodsWaitSet;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * `rmw_get_implementation_identifier()` — REP-2007 §3.
 * Returnt einen statischen NUL-terminierten String "rmw_zerodds_cpp".
 *
 * # Safety
 * Pointer ist `'static` und darf nicht freigegeben werden.
 */
 const char *rmw_zerodds_get_implementation_identifier(void);

/**
 * `rmw_get_serialization_format()` — fixed `"cdr"` (XCDR1).
 *
 * # Safety
 * Pointer ist `'static`.
 */
 const char *rmw_zerodds_get_serialization_format(void);

/**
 * `rmw_init(domain_id) -> *mut RmwZerodsContext`.
 * In aktuelle Distros nimmt sie einen einzelnen Domain-Id-Parameter.
 *
 * # Safety
 * Caller muss `rmw_zerodds_shutdown` mit dem zurueckgegebenen Handle
 * aufrufen, sonst Leak.
 */
 struct rmw_zerodds_RmwZerodsContext *rmw_zerodds_init(uint32_t domain_id);

/**
 * `rmw_shutdown(*mut Context)` — gibt die Runtime frei. NULL-safe.
 *
 * # Safety
 * `ctx` muss aus `rmw_zerodds_init` stammen oder NULL.
 */
 int32_t rmw_zerodds_shutdown(struct rmw_zerodds_RmwZerodsContext *ctx);

/**
 * `rmw_create_node(ctx, name, namespace_)` — REP-2007 §5.1.
 *
 * # Safety
 * `ctx` muss live; `name`/`namespace_` NUL-terminiert.
 */

struct rmw_zerodds_RmwZerodsNode *rmw_zerodds_create_node(struct rmw_zerodds_RmwZerodsContext *ctx,
                                                          const char *name,
                                                          const char *namespace_);

/**
 * `rmw_destroy_node(*mut Node)`. NULL-safe.
 *
 * # Safety
 * `node` muss aus `rmw_zerodds_create_node` stammen oder NULL.
 */
 int32_t rmw_zerodds_destroy_node(struct rmw_zerodds_RmwZerodsNode *node);

/**
 * `rmw_create_publisher(node, type_name, topic_name, reliable)`.
 *
 * # Safety
 * Pointer-Validitaet wie immer; Strings NUL-terminiert.
 */

struct rmw_zerodds_RmwZerodsPublisher *rmw_zerodds_create_publisher(struct rmw_zerodds_RmwZerodsNode *node,
                                                                    const char *type_name,
                                                                    const char *topic_name,
                                                                    int reliable);

/**
 * `rmw_destroy_publisher(*mut Publisher)`.
 *
 * # Safety
 * `pub_` muss aus `rmw_zerodds_create_publisher` oder NULL.
 */
 int32_t rmw_zerodds_destroy_publisher(struct rmw_zerodds_RmwZerodsPublisher *pub_);

/**
 * `rmw_publish(pub, payload, len)` — schreibt CDR-encoded bytes.
 *
 * # Safety
 * `pub_` valid; `payload` mit `len` byte lebt waehrend des Calls.
 */

int32_t rmw_zerodds_publish(struct rmw_zerodds_RmwZerodsPublisher *pub_,
                            const uint8_t *payload,
                            uintptr_t len);

/**
 * `rmw_create_subscription(node, type, topic, reliable)`.
 *
 * # Safety
 * Wie create_publisher.
 */

struct rmw_zerodds_RmwZerodsSubscription *rmw_zerodds_create_subscription(struct rmw_zerodds_RmwZerodsNode *node,
                                                                          const char *type_name,
                                                                          const char *topic_name,
                                                                          int reliable);

/**
 * `rmw_destroy_subscription(*mut Subscription)`.
 *
 * # Safety
 * `sub` muss aus `rmw_zerodds_create_subscription` oder NULL.
 */
 int32_t rmw_zerodds_destroy_subscription(struct rmw_zerodds_RmwZerodsSubscription *sub);

/**
 * `rmw_take(sub, *mut buf, *mut len)` — versucht ein Sample zu lesen.
 * Caller MUSS `rmw_zerodds_buffer_free(buf, len)` aufrufen.
 *
 * # Safety
 * Pointer-Validitaet; out_buf/out_len NULL-checked unten.
 */

int32_t rmw_zerodds_take(struct rmw_zerodds_RmwZerodsSubscription *sub,
                         uint8_t **out_buf,
                         uintptr_t *out_len);

/**
 * `rmw_zerodds_buffer_free` — dual zu zerodds_buffer_free, fuer
 * CDR-Bytes aus rmw_zerodds_take.
 *
 * # Safety
 * Wie zerodds_buffer_free.
 */
 void rmw_zerodds_buffer_free(uint8_t *buf, uintptr_t len);

/**
 * `rmw_create_client(node, service, type_name)`.
 *
 * # Safety
 * Pointer-Validitaet wie Publisher/Subscription-create.
 */

struct rmw_zerodds_RmwZerodsClient *rmw_zerodds_create_client(struct rmw_zerodds_RmwZerodsNode *node,
                                                              const char *service_name,
                                                              const char *type_name);

/**
 * `rmw_destroy_client(*mut Client)`.
 *
 * # Safety
 * `client` aus `rmw_zerodds_create_client` oder NULL.
 */
 int32_t rmw_zerodds_destroy_client(struct rmw_zerodds_RmwZerodsClient *client);

/**
 * `rmw_send_request(client, payload, len)`.
 *
 * # Safety
 * `client` valid; payload + len lebt waehrend des Calls.
 */

int32_t rmw_zerodds_send_request(struct rmw_zerodds_RmwZerodsClient *client,
                                 const uint8_t *payload,
                                 uintptr_t len);

/**
 * `rmw_take_response(client, *mut buf, *mut len)`.
 *
 * # Safety
 * Wie rmw_zerodds_take.
 */

int32_t rmw_zerodds_take_response(struct rmw_zerodds_RmwZerodsClient *client,
                                  uint8_t **out_buf,
                                  uintptr_t *out_len);

/**
 * `rmw_create_service(node, service, type_name)` — Server-side.
 *
 * # Safety
 * Wie rmw_zerodds_create_client.
 */

struct rmw_zerodds_RmwZerodsService *rmw_zerodds_create_service(struct rmw_zerodds_RmwZerodsNode *node,
                                                                const char *service_name,
                                                                const char *type_name);

/**
 * `rmw_destroy_service(*mut Service)`.
 *
 * # Safety
 * `service` aus `rmw_zerodds_create_service` oder NULL.
 */
 int32_t rmw_zerodds_destroy_service(struct rmw_zerodds_RmwZerodsService *service);

/**
 * `rmw_take_request(service, *mut buf, *mut len)`.
 *
 * # Safety
 * Pointer-Validitaet wie rmw_zerodds_take.
 */

int32_t rmw_zerodds_take_request(struct rmw_zerodds_RmwZerodsService *service,
                                 uint8_t **out_buf,
                                 uintptr_t *out_len);

/**
 * `rmw_send_response(service, payload, len)`.
 *
 * # Safety
 * Wie rmw_zerodds_publish.
 */

int32_t rmw_zerodds_send_response(struct rmw_zerodds_RmwZerodsService *service,
                                  const uint8_t *payload,
                                  uintptr_t len);

/**
 * `rmw_create_wait_set()`.
 *
 * # Safety
 * Result-Pointer ist heap-allokiert; Caller muss
 * `rmw_zerodds_destroy_wait_set` aufrufen.
 */
 struct rmw_zerodds_RmwZerodsWaitSet *rmw_zerodds_create_wait_set(void);

/**
 * `rmw_destroy_wait_set(*mut WaitSet)`.
 *
 * # Safety
 * `ws` aus `rmw_zerodds_create_wait_set` oder NULL.
 */
 int32_t rmw_zerodds_destroy_wait_set(struct rmw_zerodds_RmwZerodsWaitSet *ws);

/**
 * Fuegt eine Subscription zum Wait-Set hinzu.
 *
 * # Safety
 * `ws` + `sub` muessen valid sein.
 */

int32_t rmw_zerodds_wait_set_add_subscription(struct rmw_zerodds_RmwZerodsWaitSet *ws,
                                              struct rmw_zerodds_RmwZerodsSubscription *sub);

/**
 * Phase-C Wait: pollt alle Subscriptions im Wait-Set mit adaptivem
 * Backoff. Edge-Trigger-Emulation:
 * * Erste 100 µs spin_loop_hint (sub-µs Latenz)
 * * 100 µs..10 ms: 10 µs Sleep
 * * 10..100 ms: 100 µs Sleep
 * * Danach: 1 ms Sleep
 *
 * Echter Edge-Trigger ueber Condvar/Channel braucht eine Notify-
 * Bruecke aus dem Reader-Receive-Thread (Phase-D).
 *
 * # Safety
 * `ws` muss valid sein.
 */
 int32_t rmw_zerodds_wait(struct rmw_zerodds_RmwZerodsWaitSet *ws, uint64_t timeout_ms);

/**
 * `rmw_borrow_loaned_message(publisher, len, *out_ptr, *out_len)` —
 * reserviert einen Buffer beim Writer fuer Zero-Copy-Publish.
 * Phase-C: malloc-backed (kein echter Zero-Copy, aber Code-Pfad
 * stabil). Phase-D wechselt auf SHM-Buffer-Pool wenn der
 * Writer auf einem SHM-Transport sitzt.
 *
 * # Safety
 * `pub_` muss aus rmw_zerodds_create_publisher stammen.
 */

int32_t rmw_zerodds_borrow_loaned_message(struct rmw_zerodds_RmwZerodsPublisher *pub_,
                                          uintptr_t len,
                                          uint8_t **out_ptr,
                                          uintptr_t *out_len);

/**
 * Commit-Pfad fuer einen Loan — schreibt den Buffer als Sample und
 * gibt ihn frei.
 *
 * # Safety
 * `pub_` valid; `ptr`/`len` aus rmw_zerodds_borrow_loaned_message.
 */

int32_t rmw_zerodds_publish_loaned_message(struct rmw_zerodds_RmwZerodsPublisher *pub_,
                                           uint8_t *ptr,
                                           uintptr_t len);

/**
 * Verwirft einen Loan ohne ihn zu publishen.
 *
 * # Safety
 * Wie rmw_zerodds_publish_loaned_message.
 */

int32_t rmw_zerodds_return_loaned_message(struct rmw_zerodds_RmwZerodsPublisher *pub_,
                                          uint8_t *ptr,
                                          uintptr_t len);

/**
 * REP-2009 Type-Hash: SHA-256 ueber den IDL-Type-String.
 * Liefert exakt 32 byte in `out_hash` (muss 32-byte-Buffer sein).
 *
 * # Safety
 * `type_str` NUL-terminierter C-String; `out_hash` zeigt auf einen
 * 32-byte-Buffer.
 */
 int32_t rmw_zerodds_compute_type_hash(const char *type_str, uint8_t *out_hash);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RMW_ZERODDS_H_ */
