[package]
name = "zerodds-idl-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[dependencies.zerodds-idl]
path = ".."

[workspace]

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false

[profile.release]
debug = 1
