cmake_minimum_required(VERSION 3.21 FATAL_ERROR)

# cmake-format: off
#
# Function returning all extensions of the files that will be generated by the given backend
#
#   zerodds_idlc_extensions_from_backend(BACKEND <rust|cpp|c|csharp|java|python|ts>
#                                        OUT_VAR <variable_in_output>
#   )
#
#   - BACKEND: is the backend used for generating source code
#   - OUT_VAR: is the variable name that will be set containing the files extension
# cmake-format: on
function(zerodds_idlc_extensions_from_backend BACKEND OUT_VAR)
    # List of available extensions used in following regex, final semicolon is added only to
    # allow correct resolution of `ts` case
    set(GENERABLE_EXTENSIONS "rust=.rs;cpp=.hpp;c=.h;csharp=.cs;java=.java;python=.py;ts=.ts;")

    # If is requested generation for all supported types
    # return directly all the extensions
    if(BACKEND STREQUAL "all")
        set(${OUT_VAR} ".rs;.hpp;.h;.cs;.java;.py;.ts" PARENT_SCOPE)
    elseif(GENERABLE_EXTENSIONS MATCHES "${BACKEND}=(\.[a-z]*);")
        set(${OUT_VAR} ${CMAKE_MATCH_1} PARENT_SCOPE)
    endif()
endfunction()

# cmake-format: off
# Function wrapping the zerodds-idlc executable and generating source files from IDL
#
#   zerodds_idlc_generate( LIBRARY_NAME <generated_idl_library_name>
#                          IDL_FILES <list_of_idl_files>
#                          GENERATOR_BACKEND <cpp|c|rust|csharp|java|python|ts>
#                          [OUTPUT_DIR <destination_folder>]
#                          [BASE_DIR <subfolder_of_idl>]
#                          [IDL_INCLUDE_DIRS <list_of_folders_to_search_for_idl>]
#                          [LIBRARY_NAMESPACE <namespace added to LIBRARY_NAME>]
#                          [GENERATOR_FLAGS <list_of_flags_for_generator>]
#   )
#
# - LIBRARY_NAME: name of the library that will be created by CMake
# - IDL_FILES: list of IDL files that will be compiled and associated to LIBRARY_NAME
# - GENERATOR_BACKEND: which kind of generator to use when compiling IDL sources
# - OUTPUT_DIR: folder in which compiled IDL files will be put, and also folder to which the
#               library will have access thanks to target_include_directory directive.
#               Default: `${CMAKE_CURRENT_BINARY_DIR}/zerodds/idl`
# - BASE_DIR: subfolder beloning to IDL_FILES since which the directory tree will be preserved, thus
#             organization of compiled IDL files will be unchanged in OUTPUT_DIR folder
# - IDL_INCLUDE_DIRS: directories in which to search IDL files addressed by #include directive
#                     during IDL parsing
# - LIBRARY_NAMESPACE: namespace for the generated library. Default is `zerodds-idlc`
# - GENERATOR_FLAGS: further generator flags not handled directly by CMake that will
#                    be forwarded to zerodds-idlc
# cmake-format: on
function(zerodds_idlc_generate LIBRARY_NAME)
    include(CMakeParseArguments)

    set(_options "")
    set(_singleargs OUTPUT_DIR LIBRARY_NAMESPACE GENERATOR_BACKEND BASE_DIR)
    set(_multiargs IDL_FILES GENERATOR_FLAGS IDL_INCLUDE_DIRS)
    cmake_parse_arguments(PARSE_ARGV 1 "" "${_options}" "${_singleargs}" "${_multiargs}")

    # If output dir is not given, use the project binary one followed by include/zerodds/idl
    # thus allowing #include<zerodds/idl/*.idl>
    if(NOT _OUTPUT_DIR)
        set(_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/zerodds/idl")
    endif()

    # Check GENERATOR_BACKEND validity: only `cpp` and `c` can be used for generating linkable
    # CMake libraries, in all other cases an OBJECT library will be created
    if(NOT _GENERATOR_BACKEND)
        message(FATAL_ERROR "GENERATOR_BACKEND is a compulsory flag")
    endif()

    # If zerodds-idlc target is not defined, call cargo to build it
    if(NOT TARGET zerodds::zerodds-idlc)
        # CARGO_EXECUTABLE should have been defined in the root CMakeLists.txt
        # anyway search it again and throw error if not found
        if(NOT CARGO_EXECUTABLE)
            find_program(CARGO_EXECUTABLE NAMES cargo)
            if("${CARGO_EXECUTABLE}" STREQUAL "CARGO_EXECUTABLE-NOTFOUND")
            message(FATAL_ERROR "Cargo not found. Look at: https://rust-lang.org/learn/get-started")
            endif()
        endif()

        # Set OS-Specific executable extension
        if(WIN32)
            set(ZERODDS_IDLC_EXE_EXTENSION ".exe")
        endif()

        # Run rustc for building zerodds-idlc in Release
        # The build executable will be put in the caller project binary directory
        add_custom_target(zerodds_idlc_build ALL
            ${CARGO_EXECUTABLE} "rustc" "--manifest-path" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../Cargo.toml"
                                "--package" "zerodds-idlc" "--release"
                                "--target-dir" "${CMAKE_CURRENT_BINARY_DIR}"
        )

        # Define zerodds-idlc as imported executable generated by `zerodds_idlc_build`
        add_executable(zerodds::zerodds-idlc IMPORTED GLOBAL)
        add_dependencies(zerodds::zerodds-idlc zerodds_idlc_build)
        set_target_properties(zerodds::zerodds-idlc PROPERTIES
            IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/release/zerodds-idlc${ZERODDS_IDLC_EXE_EXTENSION}"
        )
    endif()

    # Get compiled IDL files extension
    zerodds_idlc_extensions_from_backend(${_GENERATOR_BACKEND} EXPECTED_GENERATED_EXTENSIONS)

    # Generate compiled .idl files
    set(EXPECTED_GENERATED_SOURCES)
    foreach(extension IN LISTS EXPECTED_GENERATED_EXTENSIONS)
        foreach(idl_source IN LISTS _IDL_FILES)
            get_filename_component(idl_filename ${idl_source} NAME)
            get_filename_component(idl_directory_tree ${idl_source} DIRECTORY)

            if(_BASE_DIR)
                string(REPLACE "${_BASE_DIR}" "" expected_directory ${idl_directory_tree})
            endif()
            string(REPLACE ".idl" ${extension} expected_filename ${idl_filename})

            set(EXPECTED_SOURCE_FILEPATH ${_OUTPUT_DIR}/${expected_directory}/${expected_filename})

            add_custom_command(
                OUTPUT ${EXPECTED_SOURCE_FILEPATH}
                COMMAND zerodds::zerodds-idlc "generate" ${idl_source} 
                                              "--${_GENERATOR_BACKEND}"
                                              "--output" "${_OUTPUT_DIR}/${expected_directory}"
                                              $<$<BOOL:${IDLC_INCLUDE_DIRS_FLAG}>:"-I ${_IDL_INCLUDE_DIRS}">
                                              "${GENERATOR_FLAGS}"
                DEPENDS ${idl_source}
            )

            # update variable that will be feeded to library
            list(APPEND EXPECTED_GENERATED_SOURCES ${EXPECTED_SOURCE_FILEPATH})
        endforeach()
    endforeach()

    # Generate the library and link it to the correct CMake target and directories
    # Library can be only of INTERFACE type because in C and C++ the generator outputs
    # only headers, and in other languages the outputs cannot be compiled
    add_library(${LIBRARY_NAME} INTERFACE ${EXPECTED_GENERATED_SOURCES})

    if(${_GENERATOR_BACKEND} STREQUAL "c" OR ${_GENERATOR_BACKEND} STREQUAL "cpp")
        set_target_properties(${LIBRARY_NAME} PROPERTIES
            LINKER_LANGUAGE $<IF:$<STREQUAL: "${_GENERATOR_BACKEND}" , "c" >, "C" , "CXX" >
        )
        target_link_libraries(${LIBRARY_NAME} INTERFACE
            $<$<STREQUAL:"${_GENERATOR_BACKEND}","c">: zerodds::zerodds-c>
            $<$<STREQUAL:"${_GENERATOR_BACKEND}","cpp">: zerodds::zerodds-cpp>
        )
        target_include_directories(${LIBRARY_NAME} INTERFACE ${_OUTPUT_DIR})
    endif()

    # Expose the library with the given namespace if specified
    # otherwise use the default namespace zerodds-idlc
    if(LIBRARY_NAMESPACE)
        add_library(${LIBRARY_NAMESPACE}::${LIBRARY_NAME} ALIAS ${LIBRARY_NAME})
    else()
        add_library(zerodds-idlc::${LIBRARY_NAME} ALIAS ${LIBRARY_NAME})
    endif()

endfunction()
