// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ZeroDDS Contributors

using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZeroDDS.Cdr.SourceGenerators;

/// <summary>
/// Roslyn Source-Generator: emits an <c>IDdsTopicType&lt;T&gt;</c> companion
/// class for every <c>partial class</c> annotated with <c>[DdsType]</c>.
///
/// Implements <c>zerodds-xcdr2-csharp-1.0</c> §11.4. The generator is
/// triggered at compile-time and produces a <c>{Name}TypeSupport</c>
/// singleton class with byte-identical XCDR2 wire output to the
/// hand-written <c>idl-csharp</c> codegen.
///
/// Supported field types in v1.0: <c>int</c>, <c>uint</c>, <c>short</c>,
/// <c>ushort</c>, <c>long</c>, <c>ulong</c>, <c>byte</c>, <c>bool</c>,
/// <c>float</c>, <c>double</c>, <c>string</c>. Nested structs and
/// collections require the IDL-driven <c>idl-csharp</c> codegen.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DdsTypeGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace ZeroDDS.Cdr
{
    /// <summary>Marks a partial class for a source-generator-emitted
    /// IDdsTopicType&lt;T&gt;.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct,
        AllowMultiple = false, Inherited = false)]
    public sealed class DdsTypeAttribute : System.Attribute
    {
        public string? TypeName { get; set; }
        public string Extensibility { get; set; } = ""final"";
    }

    [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field,
        AllowMultiple = false, Inherited = false)]
    public sealed class DdsKeyAttribute : System.Attribute { }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the [DdsType] / [DdsKey] attributes once.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("DdsTypeAttributes.g.cs", AttributeSource));

        var classes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ZeroDDS.Cdr.DdsTypeAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(classes, static (spc, sym) =>
        {
            var src = Emit(sym);
            spc.AddSource($"{sym.Name}TypeSupport.g.cs", src);
        });
    }

    private static string Emit(INamedTypeSymbol cls)
    {
        var ns = cls.ContainingNamespace.IsGlobalNamespace
            ? null
            : cls.ContainingNamespace.ToDisplayString();

        var typeNameOverride = (string?)null;
        var extensibility = "Final";
        foreach (var attr in cls.GetAttributes())
        {
            if (attr.AttributeClass?.Name != "DdsTypeAttribute") continue;
            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "TypeName" && named.Value.Value is string s)
                    typeNameOverride = s;
                else if (named.Key == "Extensibility" && named.Value.Value is string e)
                    extensibility = e switch
                    {
                        "appendable" => "Appendable",
                        "mutable" => "Mutable",
                        _ => "Final",
                    };
            }
        }

        var typeName = typeNameOverride ?? cls.Name;

        // Walk properties + fields. Detect [DdsKey] markers.
        // Skip implicit (auto-property backing) fields + static + const.
        var members = new List<(string Name, string Type, bool IsKey)>();
        foreach (var m in cls.GetMembers())
        {
            if (m.IsImplicitlyDeclared || m.IsStatic) continue;
            if (m is IPropertySymbol p && p.SetMethod != null && !p.IsIndexer)
            {
                bool isKey = HasAttr(p, "DdsKeyAttribute");
                members.Add((p.Name, p.Type.ToDisplayString(), isKey));
            }
            else if (m is IFieldSymbol f && !f.IsConst && !f.IsImplicitlyDeclared)
            {
                bool isKey = HasAttr(f, "DdsKeyAttribute");
                members.Add((f.Name, f.Type.ToDisplayString(), isKey));
            }
        }

        bool isKeyed = members.Exists(m => m.IsKey);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using ZeroDDS.Cdr;");
        sb.AppendLine();
        if (ns != null)
        {
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
        }
        sb.Append("    public sealed class ").Append(cls.Name)
            .Append("TypeSupport : IDdsTopicType<").Append(cls.Name).AppendLine(">");
        sb.AppendLine("    {");
        sb.Append("        public static readonly ").Append(cls.Name)
            .Append("TypeSupport Instance = new ")
            .Append(cls.Name).AppendLine("TypeSupport();");
        sb.AppendLine();
        sb.Append("        public string TypeName => \"").Append(typeName).AppendLine("\";");
        sb.Append("        public bool IsKeyed => ").Append(isKeyed ? "true" : "false").AppendLine(";");
        sb.Append("        public ExtensibilityKind Extensibility => ExtensibilityKind.")
            .Append(extensibility).AppendLine(";");
        sb.AppendLine();
        sb.Append("        public byte[] Encode(").Append(cls.Name)
            .AppendLine(" sample) => Encode(sample, EndianMode.LittleEndian);");
        sb.AppendLine();
        sb.Append("        public byte[] Encode(").Append(cls.Name).AppendLine(" sample, EndianMode endian)");
        sb.AppendLine("        {");
        sb.AppendLine("            var w = new Xcdr2Writer(endian);");
        foreach (var m in members)
        {
            sb.Append("            ").Append(WriteCall(m.Type, $"sample.{m.Name}")).AppendLine();
        }
        sb.AppendLine("            return w.ToArray();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        public ").Append(cls.Name).AppendLine(" Decode(ReadOnlySpan<byte> bytes)");
        sb.AppendLine("        {");
        sb.AppendLine("            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);");
        sb.Append("            return new ").Append(cls.Name).AppendLine("");
        sb.AppendLine("            {");
        for (int i = 0; i < members.Count; i++)
        {
            var m = members[i];
            sb.Append("                ").Append(m.Name).Append(" = ")
                .Append(ReadCall(m.Type)).Append(',').AppendLine();
        }
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        public byte[] KeyHash(").Append(cls.Name).AppendLine(" sample)");
        sb.AppendLine("        {");
        if (isKeyed)
        {
            sb.AppendLine("            var w = new Xcdr2Writer(EndianMode.BigEndian);");
            foreach (var m in members)
            {
                if (!m.IsKey) continue;
                sb.Append("            ").Append(WriteCall(m.Type, $"sample.{m.Name}")).AppendLine();
            }
            sb.AppendLine("            var holder = w.ToArray();");
            sb.AppendLine("            // XTypes 1.3 §7.6.8.4: holder ≤ 16 octets -> zero-pad; otherwise MD5.");
            sb.AppendLine("            if (holder.Length <= 16)");
            sb.AppendLine("            {");
            sb.AppendLine("                var h = new byte[16];");
            sb.AppendLine("                Buffer.BlockCopy(holder, 0, h, 0, holder.Length);");
            sb.AppendLine("                return h;");
            sb.AppendLine("            }");
            sb.AppendLine("            return Md5.Hash(holder);");
        }
        else
        {
            sb.AppendLine("            return new byte[16];");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        if (ns != null) sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool HasAttr(ISymbol s, string name)
    {
        foreach (var a in s.GetAttributes())
            if (a.AttributeClass?.Name == name) return true;
        return false;
    }

    private static string WriteCall(string type, string expr) => type switch
    {
        "int" or "System.Int32" => $"w.WriteInt32({expr});",
        "uint" or "System.UInt32" => $"w.WriteUInt32({expr});",
        "short" or "System.Int16" => $"w.WriteInt16({expr});",
        "ushort" or "System.UInt16" => $"w.WriteUInt16({expr});",
        "long" or "System.Int64" => $"w.WriteInt64({expr});",
        "ulong" or "System.UInt64" => $"w.WriteUInt64({expr});",
        "byte" or "System.Byte" => $"w.WriteUInt8({expr});",
        "sbyte" or "System.SByte" => $"w.WriteInt8({expr});",
        "bool" or "System.Boolean" => $"w.WriteBoolean({expr});",
        "float" or "System.Single" => $"w.WriteFloat32({expr});",
        "double" or "System.Double" => $"w.WriteFloat64({expr});",
        "string" or "System.String" => $"w.WriteString({expr});",
        _ => $"// unsupported: {type} {expr}",
    };

    private static string ReadCall(string type) => type switch
    {
        "int" or "System.Int32" => "r.ReadInt32()",
        "uint" or "System.UInt32" => "r.ReadUInt32()",
        "short" or "System.Int16" => "r.ReadInt16()",
        "ushort" or "System.UInt16" => "r.ReadUInt16()",
        "long" or "System.Int64" => "r.ReadInt64()",
        "ulong" or "System.UInt64" => "r.ReadUInt64()",
        "byte" or "System.Byte" => "r.ReadUInt8()",
        "sbyte" or "System.SByte" => "r.ReadInt8()",
        "bool" or "System.Boolean" => "r.ReadBoolean()",
        "float" or "System.Single" => "r.ReadFloat32()",
        "double" or "System.Double" => "r.ReadFloat64()",
        "string" or "System.String" => "r.ReadString()",
        _ => "default",
    };
}
