# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from typing import List
from zerodds.idl import idl_struct, BoundedString, BoundedWString, Int32, Map, Sequence, String

@idl_struct(typename="b::Bounded", extensibility="appendable")
@dataclass
class b_Bounded:
    nums: Sequence[Int32, 3]
    name: BoundedString[5]
    wname: BoundedWString[3]
    counters: Map[String, Int32, 2]
    unbounded: List[Int32]
    fullstr: String

