# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from typing import Dict, List
from zerodds.idl import idl_struct, Int32, String

@idl_struct(typename="d::L3", extensibility="appendable")
@dataclass
class d_L3:
    v: Int32

@idl_struct(typename="d::L2", extensibility="appendable")
@dataclass
class d_L2:
    inner: d_L3

@idl_struct(typename="d::L1", extensibility="appendable")
@dataclass
class d_L1:
    inner: d_L2

@idl_struct(typename="d::HasSeq", extensibility="appendable")
@dataclass
class d_HasSeq:
    xs: List[Int32]

@idl_struct(typename="d::Deep", extensibility="appendable")
@dataclass
class d_Deep:
    chain: d_L1
    grid: List[List[d_L3]]
    table: Dict[String, d_HasSeq]

