# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from zerodds.idl import idl_struct, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8

@idl_struct(typename="Extremes", extensibility="appendable")
@dataclass
class Extremes:
    i8: Int8
    u8: UInt8
    i16: Int16
    u16: UInt16
    i32: Int32
    u32: UInt32
    i64: Int64
    u64: UInt64
    f: Float32
    dbl: Float64

