# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from zerodds.idl import idl_struct, Int32, Int64, String

@idl_struct(typename="Keyed", extensibility="appendable")
@dataclass
class Keyed:
    id: Int32
    label: String
    payload: Int64

