# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from typing import Dict, List
from zerodds.idl import idl_struct, Int32, Optional, String

@idl_struct(typename="o::Inner", extensibility="appendable")
@dataclass
class o_Inner:
    v: Int32

@idl_struct(typename="o::OptAgg", extensibility="appendable")
@dataclass
class o_OptAgg:
    nested: Optional[o_Inner]
    nums: Optional[List[Int32]]
    table: Optional[Dict[String, Int32]]
    note: Optional[String]

