# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from zerodds.idl import idl_struct, String, WString

@idl_struct(typename="Uni", extensibility="appendable")
@dataclass
class Uni:
    s: String
    w: WString

