[package]
name = "zerodds-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Idiomatic Rust SDK, async/await, streams"
homepage = "https://zerodds.org"
documentation = "https://docs.rs/zerodds-rs"
readme = "README.md"
keywords = ["dds", "rust", "sdk", "facade"]
categories = ["network-programming", "api-bindings"]
publish = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
safety = []

[dependencies]
zerodds-dcps = { version = "1.0.0-rc.6", path = "../dcps" }
zerodds-dcps-async = { version = "1.0.0-rc.6", path = "../dcps-async" }
zerodds-qos = { version = "1.0.0-rc.6", path = "../qos" }
zerodds-types = { version = "1.0.0-rc.6", path = "../types" }
zerodds-monitor = { version = "1.0.0-rc.6", path = "../monitor" }
zerodds-recorder = { version = "1.0.0-rc.6", path = "../recorder" }
zerodds-foundation = { version = "1.0.0-rc.6", path = "../foundation" }

[dev-dependencies]
